// GENERATED by tools/design/generate.py from DESIGN.md — DO NOT EDIT.

/// Corner radii.
abstract final class AppRadius {
  static const double xs = 4;
  static const double sm = 8;
  static const double md = 12;
  static const double lg = 16;
  static const double xl = 20;
  static const double full = 999;
}
