// GENERATED by tools/design/generate.py from DESIGN.md — DO NOT EDIT.
import 'package:flutter/material.dart';

/// One named shadow: an offset, a blur and an alpha over the scheme's `shadow` role.
@immutable
final class AppShadow {
  const AppShadow({required this.dy, required this.blur, required this.alpha});

  final double dy;
  final double blur;
  final double alpha;

  BoxShadow on(Color shadow) => BoxShadow(
    color: shadow.withValues(alpha: alpha),
    offset: Offset(0, dy),
    blurRadius: blur,
  );
}

/// DESIGN.md's shadow vocabulary; `null` where a theme draws none.
abstract final class AppShadows {
  static const AppShadow whisperLight = AppShadow(dy: 1, blur: 2, alpha: 0.04);
  static const AppShadow? whisperDark = null;
  static const AppShadow chromeLight = AppShadow(dy: -2, blur: 12, alpha: 0.05);
  static const AppShadow chromeDark = AppShadow(dy: -2, blur: 14, alpha: 0.36);
  static const AppShadow overlayLight = AppShadow(dy: 12, blur: 32, alpha: 0.1);
  static const AppShadow overlayDark = AppShadow(dy: 16, blur: 40, alpha: 0.42);
}
