// GENERATED by tools/design/generate.py from DESIGN.md — DO NOT EDIT.

/// Stroke widths.
abstract final class AppStroke {
  static const double hairline = 1;
  static const double control = 2;
  static const double focus = 2;
  static const double indicator = 6;
}
