// GENERATED by tools/design/generate.py from DESIGN.md — DO NOT EDIT.

/// Motion and dwell durations.
abstract final class AppDurations {
  static const Duration toggle = Duration(milliseconds: 160);
  static const Duration standard = Duration(milliseconds: 200);
  static const Duration scrimFade = Duration(milliseconds: 220);
  static const Duration sheet = Duration(milliseconds: 260);
  static const Duration settle = Duration(milliseconds: 400);
  static const Duration repeat = Duration(milliseconds: 80);
  static const Duration spinnerCycle = Duration(milliseconds: 800);
  static const Duration skeletonPulse = Duration(milliseconds: 1400);
  static const Duration toast = Duration(milliseconds: 4000);
  static const Duration toastWithUndo = Duration(milliseconds: 8000);
}
