// GENERATED by tools/design/generate.py from DESIGN.md — DO NOT EDIT.

/// The spacing steps.
abstract final class AppSpacing {
  static const double micro = 4;
  static const double control = 8;
  static const double grouped = 12;
  static const double gutter = 16;
  static const double card = 20;
  static const double section = 24;
  static const double major = 32;
  static const double pageEnd = 48;
}
