// GENERATED by tools/design/generate.py from DESIGN.md — DO NOT EDIT.

/// Window-width breakpoints.
abstract final class AppBreakpoints {
  static const double navRail = 600;
  static const double contentMax = 720;
}
