// GENERATED by tools/design/generate.py from DESIGN.md — DO NOT EDIT.

/// Named opacities.
abstract final class AppOpacity {
  static const double disabled = 0.38;
  static const double muted = 0.7;
  static const double pressed = 0.12;
  static const double focus = 0.12;
  static const double scrim = 0.45;
  static const double glass = 0.84;
  static const double skeletonLow = 0.45;
  static const double skeletonHigh = 0.75;
}
