// GENERATED by tools/design/generate.py from DESIGN.md — DO NOT EDIT.
import 'package:flutter/material.dart';

/// MemoX semantic colours beside the Material 3 scheme (spec 2026-10-04-sp3a A2).
@immutable
final class AppSemanticColors extends ThemeExtension<AppSemanticColors> {
  const AppSemanticColors({
    required this.success,
    required this.onSuccess,
    required this.successContainer,
    required this.onSuccessContainer,
    required this.warning,
    required this.onWarning,
    required this.warningContainer,
    required this.onWarningContainer,
    required this.statusNew,
    required this.statusNewContainer,
    required this.onStatusNewContainer,
    required this.statusLearning,
    required this.statusLearningContainer,
    required this.onStatusLearningContainer,
    required this.statusReviewing,
    required this.statusReviewingContainer,
    required this.onStatusReviewingContainer,
    required this.statusMastered,
    required this.statusMasteredContainer,
    required this.onStatusMasteredContainer,
    required this.streak,
  });

  static const AppSemanticColors light = AppSemanticColors(
    success: Color(0xFF176B57),
    onSuccess: Color(0xFFFFFFFF),
    successContainer: Color(0xFFD5F2E9),
    onSuccessContainer: Color(0xFF0B3B2F),
    warning: Color(0xFF90570C),
    onWarning: Color(0xFFFFFFFF),
    warningContainer: Color(0xFFFCEFC7),
    onWarningContainer: Color(0xFF3A2A00),
    statusNew: Color(0xFF60646F),
    statusNewContainer: Color(0xFFEAE9E4),
    onStatusNewContainer: Color(0xFF2B3150),
    statusLearning: Color(0xFF4F501F),
    statusLearningContainer: Color(0xFFDFE5BE),
    onStatusLearningContainer: Color(0xFF352C00),
    statusReviewing: Color(0xFF256A93),
    statusReviewingContainer: Color(0xFFD3EAF0),
    onStatusReviewingContainer: Color(0xFF12324E),
    statusMastered: Color(0xFF1A6B48),
    statusMasteredContainer: Color(0xFFD3F0E2),
    onStatusMasteredContainer: Color(0xFF0A3B25),
    streak: Color(0xFFE8620C),
  );

  static const AppSemanticColors dark = AppSemanticColors(
    success: Color(0xFF5FD3B4),
    onSuccess: Color(0xFF06362A),
    successContainer: Color(0xFF14473A),
    onSuccessContainer: Color(0xFFC9F5E7),
    warning: Color(0xFFE1994E),
    onWarning: Color(0xFF3A2A00),
    warningContainer: Color(0xFF4A3610),
    onWarningContainer: Color(0xFFFCE6B8),
    statusNew: Color(0xFFA2A4B0),
    statusNewContainer: Color(0xFF2B3256),
    onStatusNewContainer: Color(0xFFDDE1F2),
    statusLearning: Color(0xFFD5D789),
    statusLearningContainer: Color(0xFF38361A),
    onStatusLearningContainer: Color(0xFFF2E7B5),
    statusReviewing: Color(0xFF7CC3EA),
    statusReviewingContainer: Color(0xFF1D3A52),
    onStatusReviewingContainer: Color(0xFFD2E5F4),
    statusMastered: Color(0xFF76D3B4),
    statusMasteredContainer: Color(0xFF134733),
    onStatusMasteredContainer: Color(0xFFC6F5E2),
    streak: Color(0xFFFB8A3C),
  );

  final Color success;
  final Color onSuccess;
  final Color successContainer;
  final Color onSuccessContainer;
  final Color warning;
  final Color onWarning;
  final Color warningContainer;
  final Color onWarningContainer;
  final Color statusNew;
  final Color statusNewContainer;
  final Color onStatusNewContainer;
  final Color statusLearning;
  final Color statusLearningContainer;
  final Color onStatusLearningContainer;
  final Color statusReviewing;
  final Color statusReviewingContainer;
  final Color onStatusReviewingContainer;
  final Color statusMastered;
  final Color statusMasteredContainer;
  final Color onStatusMasteredContainer;
  final Color streak;

  @override
  AppSemanticColors copyWith({
    Color? success,
    Color? onSuccess,
    Color? successContainer,
    Color? onSuccessContainer,
    Color? warning,
    Color? onWarning,
    Color? warningContainer,
    Color? onWarningContainer,
    Color? statusNew,
    Color? statusNewContainer,
    Color? onStatusNewContainer,
    Color? statusLearning,
    Color? statusLearningContainer,
    Color? onStatusLearningContainer,
    Color? statusReviewing,
    Color? statusReviewingContainer,
    Color? onStatusReviewingContainer,
    Color? statusMastered,
    Color? statusMasteredContainer,
    Color? onStatusMasteredContainer,
    Color? streak,
  }) {
    return AppSemanticColors(
      success: success ?? this.success,
      onSuccess: onSuccess ?? this.onSuccess,
      successContainer: successContainer ?? this.successContainer,
      onSuccessContainer: onSuccessContainer ?? this.onSuccessContainer,
      warning: warning ?? this.warning,
      onWarning: onWarning ?? this.onWarning,
      warningContainer: warningContainer ?? this.warningContainer,
      onWarningContainer: onWarningContainer ?? this.onWarningContainer,
      statusNew: statusNew ?? this.statusNew,
      statusNewContainer: statusNewContainer ?? this.statusNewContainer,
      onStatusNewContainer: onStatusNewContainer ?? this.onStatusNewContainer,
      statusLearning: statusLearning ?? this.statusLearning,
      statusLearningContainer:
          statusLearningContainer ?? this.statusLearningContainer,
      onStatusLearningContainer:
          onStatusLearningContainer ?? this.onStatusLearningContainer,
      statusReviewing: statusReviewing ?? this.statusReviewing,
      statusReviewingContainer:
          statusReviewingContainer ?? this.statusReviewingContainer,
      onStatusReviewingContainer:
          onStatusReviewingContainer ?? this.onStatusReviewingContainer,
      statusMastered: statusMastered ?? this.statusMastered,
      statusMasteredContainer:
          statusMasteredContainer ?? this.statusMasteredContainer,
      onStatusMasteredContainer:
          onStatusMasteredContainer ?? this.onStatusMasteredContainer,
      streak: streak ?? this.streak,
    );
  }

  @override
  AppSemanticColors lerp(AppSemanticColors? other, double t) {
    if (other == null) {
      return this;
    }
    return AppSemanticColors(
      success: Color.lerp(success, other.success, t)!,
      onSuccess: Color.lerp(onSuccess, other.onSuccess, t)!,
      successContainer: Color.lerp(
        successContainer,
        other.successContainer,
        t,
      )!,
      onSuccessContainer: Color.lerp(
        onSuccessContainer,
        other.onSuccessContainer,
        t,
      )!,
      warning: Color.lerp(warning, other.warning, t)!,
      onWarning: Color.lerp(onWarning, other.onWarning, t)!,
      warningContainer: Color.lerp(
        warningContainer,
        other.warningContainer,
        t,
      )!,
      onWarningContainer: Color.lerp(
        onWarningContainer,
        other.onWarningContainer,
        t,
      )!,
      statusNew: Color.lerp(statusNew, other.statusNew, t)!,
      statusNewContainer: Color.lerp(
        statusNewContainer,
        other.statusNewContainer,
        t,
      )!,
      onStatusNewContainer: Color.lerp(
        onStatusNewContainer,
        other.onStatusNewContainer,
        t,
      )!,
      statusLearning: Color.lerp(statusLearning, other.statusLearning, t)!,
      statusLearningContainer: Color.lerp(
        statusLearningContainer,
        other.statusLearningContainer,
        t,
      )!,
      onStatusLearningContainer: Color.lerp(
        onStatusLearningContainer,
        other.onStatusLearningContainer,
        t,
      )!,
      statusReviewing: Color.lerp(statusReviewing, other.statusReviewing, t)!,
      statusReviewingContainer: Color.lerp(
        statusReviewingContainer,
        other.statusReviewingContainer,
        t,
      )!,
      onStatusReviewingContainer: Color.lerp(
        onStatusReviewingContainer,
        other.onStatusReviewingContainer,
        t,
      )!,
      statusMastered: Color.lerp(statusMastered, other.statusMastered, t)!,
      statusMasteredContainer: Color.lerp(
        statusMasteredContainer,
        other.statusMasteredContainer,
        t,
      )!,
      onStatusMasteredContainer: Color.lerp(
        onStatusMasteredContainer,
        other.onStatusMasteredContainer,
        t,
      )!,
      streak: Color.lerp(streak, other.streak, t)!,
    );
  }
}
