// GENERATED by tools/design/generate.py from DESIGN.md — DO NOT EDIT.

/// Glyph sizes.
abstract final class AppIconSize {
  static const double small = 16;
  static const double mark = 18;
  static const double medium = 20;
  static const double large = 24;
}
