// GENERATED by tools/design/generate.py from DESIGN.md — DO NOT EDIT.

/// Component geometry: painted sizes, the 48 target, fixed offsets.
abstract final class AppSize {
  static const double tapTarget = 48;
  static const double buttonRegular = 48;
  static const double buttonSmall = 36;
  static const double buttonCompact = 32;
  static const double buttonChip = 28;
  static const double buttonStudyPadding = 36;
  static const double iconButton = 36;
  static const double fab = 52;
  static const double field = 52;
  static const double fieldDetail = 48;
  static const double fieldMeaning = 76;
  static const double toggleWidth = 44;
  static const double toggleHeight = 26;
  static const double toggleThumb = 20;
  static const double chip = 28;
  static const double checkbox = 18;
  static const double radio = 20;
  static const double focusOffset = 2;
  static const double spinnerSmall = 16;
  static const double spinnerMedium = 20;
  static const double spinnerLarge = 32;
  static const double spinnerXlarge = 48;
  static const double segment = 36;
  static const double iconTileSmall = 32;
  static const double iconTileMedium = 40;
  static const double iconTileLarge = 48;
  static const double badge = 24;
  static const double tagChip = 24;
  static const double tagChipDense = 20;
  static const double statusDot = 8;
  static const double progress = 4;
  static const double progressThick = 8;
  static const double emptyTile = 64;
  static const double emptyTileCompact = 48;
  static const double dialogSmall = 300;
  static const double dialogMedium = 320;
  static const double dialogLarge = 340;
  static const double grabberWidth = 32;
  static const double grabberHeight = 4;
  static const double sheetTopClearance = 72;
  static const double sheetMaxWidth = 640;
}
