// GENERATED by tools/design/generate.py from DESIGN.md — DO NOT EDIT.
import 'package:flutter/material.dart';
import 'package:memox/core/theme/app_typography.dart';

/// DESIGN.md's typography roles and its TextTheme mapping.
abstract final class AppTextStyles {
  static const String family = 'PlusJakartaSans';

  static final TextStyle stat = AppTypography.withWeight(
    const TextStyle(
      fontFamily: family,
      fontSize: 40,
      height: 1,
      letterSpacing: -0.64,
      fontFeatures: <FontFeature>[FontFeature.tabularFigures()],
    ),
    FontWeight.w600,
  );

  static final TextStyle display = AppTypography.withWeight(
    const TextStyle(
      fontFamily: family,
      fontSize: 32,
      height: 1.1,
      letterSpacing: -0.64,
    ),
    FontWeight.w800,
  );

  static final TextStyle headline = AppTypography.withWeight(
    const TextStyle(
      fontFamily: family,
      fontSize: 24,
      height: 1.2,
      letterSpacing: -0.64,
    ),
    FontWeight.w700,
  );

  static final TextStyle title = AppTypography.withWeight(
    const TextStyle(
      fontFamily: family,
      fontSize: 20,
      height: 1.2,
      letterSpacing: -0.64,
    ),
    FontWeight.w700,
  );

  static final TextStyle bodyLarge = AppTypography.withWeight(
    const TextStyle(fontFamily: family, fontSize: 16, height: 1.5),
    FontWeight.w500,
  );

  static final TextStyle body = AppTypography.withWeight(
    const TextStyle(fontFamily: family, fontSize: 14, height: 1.5),
    FontWeight.w400,
  );

  static final TextStyle caption = AppTypography.withWeight(
    const TextStyle(fontFamily: family, fontSize: 12, height: 1.4),
    FontWeight.w600,
  );

  static final TextStyle buttonLabel = AppTypography.withWeight(
    const TextStyle(
      fontFamily: family,
      fontSize: 14,
      height: 1.5,
      letterSpacing: 0.1,
    ),
    FontWeight.w600,
  );

  static final TextStyle sectionLabel = AppTypography.withWeight(
    const TextStyle(
      fontFamily: family,
      fontSize: 13,
      height: 1.4,
      letterSpacing: 0.6,
      fontFeatures: <FontFeature>[FontFeature.tabularFigures()],
    ),
    FontWeight.w700,
  );

  static final TextTheme textTheme = TextTheme(
    displayLarge: stat,
    displayMedium: display,
    displaySmall: display,
    headlineLarge: headline,
    headlineMedium: headline,
    headlineSmall: title,
    titleLarge: title,
    titleMedium: bodyLarge,
    titleSmall: buttonLabel,
    bodyLarge: bodyLarge,
    bodyMedium: body,
    bodySmall: caption,
    labelLarge: buttonLabel,
    labelMedium: sectionLabel,
    labelSmall: caption,
  );
}
