#!/usr/bin/env python3
"""Generate docs/_generated/{index,traceability,open-questions}.md.

    python tools/docs/generate.py [--out DIR]

Run from the repository root. Idempotent: the same docs always produce
byte-identical output, sorted by feature then id. `--out` writes into another
directory instead of docs/_generated/ (check.py uses it to detect stale files).

This module also holds the parsing shared with check.py.

Frontmatter parser limits (no YAML dependency in this repo):
- the block is the lines between a first line `---` and the next `---`;
- each line is `key: value`; nested maps, multi-line values and block lists
  (`- item`) are not supported;
- a value is either a scalar or an inline list `[a, b]`; list items cannot
  contain commas or brackets;
- one pair of surrounding single or double quotes is stripped from a scalar;
- `#` comments are NOT stripped — `status: active  # x` reads as `active  # x`.

open-questions.md collects every line containing "OPEN QUESTION" outside
docs/_generated/, except inside ``` fences or `inline code`.
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path.cwd()
DOCS = ROOT / "docs"
GENERATED = DOCS / "_generated"
GENERATED_HEADER = "<!-- GENERATED by tools/docs/generate.py — DO NOT EDIT -->"

# Folder name → id DOMAIN, only where the two differ; otherwise DOMAIN is the
# folder name upper-cased with `-` removed. Ids were kept from the object
# codes of the previous docs layout (docs/_migration/plan.md, Q1).
DOMAIN_OVERRIDES = {
    "study-mode": "MODE",
    "tags": "TAG",
    "starter-decks": "STARTER",
    "reminders": "REMINDER",
}
SHARED_RULE_DOMAIN = "CORE"
SHARED = "shared"

TEST_DIRS = ("test", "integration_test")
TEST_SUFFIXES = (".dart",)

OPEN_QUESTION = "OPEN QUESTION"
# Mentions inside ``` fences or `inline code` describe the marker, not a question.
INLINE_CODE = re.compile(r"`[^`]*`")


@dataclass
class Doc:
    path: Path
    kind: str  # "BR" | "UC" | "ADR" | "FEATURE"
    feature: str  # feature folder name, or SHARED
    meta: dict[str, object]
    body: str
    frontmatter_error: str | None = None
    sections: list[str] = field(default_factory=list)

    @property
    def id(self) -> str:
        return str(self.meta.get("id", ""))

    @property
    def title(self) -> str:
        return str(self.meta.get("title", ""))

    @property
    def status(self) -> str:
        return str(self.meta.get("status", ""))

    def as_list(self, key: str) -> list[str]:
        value = self.meta.get(key)
        if isinstance(value, list):
            return value
        return []


# ---------------------------------------------------------------- parsing


def parse_scalar(raw: str) -> str:
    value = raw.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "'\"":
        return value[1:-1]
    return value


def parse_value(raw: str) -> object:
    value = raw.strip()
    if not (value.startswith("[") and value.endswith("]")):
        return parse_scalar(value)
    inner = value[1:-1].strip()
    if not inner:
        return []
    return [parse_scalar(item) for item in inner.split(",")]


def split_frontmatter(text: str) -> tuple[dict[str, object] | None, str, str | None]:
    """Return (meta, body, error). meta is None when the file has no block."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None, text, None
    try:
        end = next(i for i in range(1, len(lines)) if lines[i].strip() == "---")
    except StopIteration:
        return None, text, "frontmatter không có dòng `---` đóng"
    meta: dict[str, object] = {}
    for line_no, line in enumerate(lines[1:end], 2):
        if not line.strip():
            continue
        if ":" not in line:
            return meta, "\n".join(lines[end + 1 :]), f"frontmatter dòng {line_no}: thiếu `key: value`"
        key, raw = line.split(":", 1)
        meta[key.strip()] = parse_value(raw)
    return meta, "\n".join(lines[end + 1 :]), None


def iter_unfenced(text: str):
    """Yield (line_no, line) for lines outside ``` fences."""
    fenced = False
    for line_no, line in enumerate(text.splitlines(), 1):
        if line.lstrip().startswith("```"):
            fenced = not fenced
            continue
        if not fenced:
            yield line_no, line


def h2_sections(body: str) -> list[str]:
    return [line[3:].strip() for _, line in iter_unfenced(body) if line.startswith("## ")]


def classify(path: Path) -> tuple[str, str] | None:
    """Return (kind, feature) for a structured doc, None for free-form docs."""
    parts = path.relative_to(DOCS).parts
    if len(parts) == 3 and parts[0] == SHARED and parts[1] == "rules":
        return "BR", SHARED
    if len(parts) == 3 and parts[0] == SHARED and parts[1] == "decisions":
        return "ADR", SHARED
    if len(parts) == 3 and parts[0] == "features" and parts[2] == "README.md":
        return "FEATURE", parts[1]
    if len(parts) == 4 and parts[0] == "features" and parts[2] == "rules":
        return "BR", parts[1]
    if len(parts) == 4 and parts[0] == "features" and parts[2] == "usecases":
        return "UC", parts[1]
    return None


def load_docs() -> list[Doc]:
    docs: list[Doc] = []
    for path in sorted(DOCS.rglob("*.md")):
        kind_feature = classify(path)
        if kind_feature is None:
            continue
        kind, feature = kind_feature
        meta, body, error = split_frontmatter(path.read_text(encoding="utf-8"))
        docs.append(
            Doc(
                path=path,
                kind=kind,
                feature=feature,
                meta=meta or {},
                body=body,
                frontmatter_error=error if meta is not None else (error or "thiếu frontmatter"),
                sections=h2_sections(body),
            )
        )
    return docs


def domain_of(feature: str) -> str:
    if feature == SHARED:
        return SHARED_RULE_DOMAIN
    return DOMAIN_OVERRIDES.get(feature, feature.upper().replace("-", ""))


def feature_names() -> list[str]:
    root = DOCS / "features"
    if not root.is_dir():
        return []
    return sorted(p.name for p in root.iterdir() if p.is_dir())


def rel_link(target: Path, from_dir: Path) -> str:
    return Path(os.path.relpath(target, from_dir)).as_posix()


def cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip() or "—"


# ------------------------------------------------------------ derivations


def used_by(docs: list[Doc]) -> dict[str, list[str]]:
    usage: dict[str, set[str]] = {}
    for doc in docs:
        if doc.kind != "UC":
            continue
        for rule_id in doc.as_list("rules"):
            usage.setdefault(rule_id, set()).add(doc.id)
    return {rule_id: sorted(ucs) for rule_id, ucs in usage.items()}


def test_files() -> list[Path]:
    files: list[Path] = []
    for name in TEST_DIRS:
        root = ROOT / name
        if not root.is_dir():
            continue
        files += [p for p in root.rglob("*") if p.is_file() and p.suffix in TEST_SUFFIXES]
    return sorted(files)


def tests_by_id(ids: list[str]) -> dict[str, list[str]]:
    found: dict[str, list[str]] = {doc_id: [] for doc_id in ids}
    for path in test_files():
        text = path.read_text(encoding="utf-8", errors="replace")
        for doc_id in ids:
            if doc_id in text:
                found[doc_id].append(path.relative_to(ROOT).as_posix())
    return found


def group_order(docs: list[Doc]) -> list[str]:
    features = sorted({d.feature for d in docs if d.feature != SHARED} | set(feature_names()))
    return [SHARED] + features


# ------------------------------------------------------------- rendering


def render_index(docs: list[Doc]) -> str:
    usage = used_by(docs)
    lines = [GENERATED_HEADER, "", "# Index", ""]
    by_id = lambda d: d.id  # noqa: E731
    for group in group_order(docs):
        group_docs = [d for d in docs if d.feature == group]
        readme = next((d for d in group_docs if d.kind == "FEATURE"), None)
        title = f"[{group}]({rel_link(readme.path, GENERATED)})" if readme else group
        lines += [f"## {title}", ""]
        rules = sorted((d for d in group_docs if d.kind == "BR"), key=by_id)
        cases = sorted((d for d in group_docs if d.kind == "UC"), key=by_id)
        decisions = sorted((d for d in group_docs if d.kind == "ADR"), key=by_id)
        if not (rules or cases or decisions):
            lines += ["Chưa có tài liệu.", ""]
            continue
        if rules:
            lines += ["### Rules", "", "| ID | Title | Status | Summary | Used by |", "|---|---|---|---|---|"]
            for d in rules:
                users = ", ".join(usage.get(d.id, [])) or "—"
                lines.append(
                    f"| [{d.id}]({rel_link(d.path, GENERATED)}) | {cell(d.title)} | {cell(d.status)} "
                    f"| {cell(str(d.meta.get('summary', '')))} | {users} |"
                )
            lines.append("")
        for heading, items in (("Use cases", cases), ("Decisions", decisions)):
            if not items:
                continue
            lines += [f"### {heading}", "", "| ID | Title | Status | Summary |", "|---|---|---|---|"]
            for d in items:
                lines.append(
                    f"| [{d.id}]({rel_link(d.path, GENERATED)}) | {cell(d.title)} | {cell(d.status)} "
                    f"| {cell(str(d.meta.get('summary', '')))} |"
                )
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_traceability(docs: list[Doc]) -> str:
    cases = sorted((d for d in docs if d.kind == "UC"), key=lambda d: (d.feature, d.id))
    tests = tests_by_id([d.id for d in cases])
    lines = [
        GENERATED_HEADER,
        "",
        "# Traceability",
        "",
        "Use case → rules → code → test. Test = file trong "
        + ", ".join(f"`{name}/`" for name in TEST_DIRS)
        + " có chứa chuỗi ID của UC.",
        "",
        "| UC | Status | Rules | Code | Tests |",
        "|---|---|---|---|---|",
    ]
    for d in cases:
        lines.append(
            f"| [{d.id}]({rel_link(d.path, GENERATED)}) | {cell(d.status)} "
            f"| {cell(', '.join(d.as_list('rules')))} "
            f"| {cell(', '.join(f'`{c}`' for c in d.as_list('code')))} "
            f"| {cell(', '.join(f'`{t}`' for t in tests[d.id]))} |"
        )
    if not cases:
        lines.append("| — | — | — | — | — |")
    return "\n".join(lines) + "\n"


def render_open_questions() -> str:
    lines = [GENERATED_HEADER, "", "# Open questions", ""]
    count = 0
    for path in sorted(DOCS.rglob("*.md")):
        if GENERATED in path.parents:
            continue
        hits = [
            (line_no, line.strip())
            for line_no, line in iter_unfenced(path.read_text(encoding="utf-8"))
            if OPEN_QUESTION in INLINE_CODE.sub("", line)
        ]
        if not hits:
            continue
        link = rel_link(path, GENERATED)
        lines += [f"## [{path.relative_to(DOCS).as_posix()}]({link})", ""]
        for line_no, text in hits:
            lines.append(f"- L{line_no}: {rebase_links(text, path.parent, GENERATED)}")
            count += 1
        lines.append("")
    if count == 0:
        lines += ["Không có.", ""]
    return "\n".join(lines).rstrip() + "\n"


MD_LINK = re.compile(r"(\[[^\]]*\]\()([^)\s]+)(\))")


def rebase_links(text: str, from_dir: Path, to_dir: Path) -> str:
    """Rewrite relative markdown links so they still resolve from to_dir."""

    def fix(match: re.Match[str]) -> str:
        target = match[2]
        if re.match(r"^[a-z][a-z0-9+.-]*:", target, re.I) or target.startswith("#"):
            return match[0]
        file_part, _, anchor = target.partition("#")
        moved = rel_link(from_dir / file_part, to_dir) + (f"#{anchor}" if anchor else "")
        return f"{match[1]}{moved}{match[3]}"

    return MD_LINK.sub(fix, text)


def render_all() -> dict[str, str]:
    docs = load_docs()
    return {
        "index.md": render_index(docs),
        "traceability.md": render_traceability(docs),
        "open-questions.md": render_open_questions(),
    }


def write_all(out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, content in render_all().items():
        (out_dir / name).write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=GENERATED, help="thư mục đích (mặc định docs/_generated)")
    args = parser.parse_args()
    if not DOCS.is_dir():
        print("ERROR docs: không tìm thấy — chạy từ root repo")
        return 1
    write_all(args.out)
    print(f"OK {args.out.relative_to(ROOT) if args.out.is_relative_to(ROOT) else args.out}: đã sinh 3 file")
    return 0


if __name__ == "__main__":
    sys.exit(main())
