#!/usr/bin/env python3
"""Generate docs/_generated/{index,traceability,screens,navigation-graph,open-questions}.md.

    python tools/docs/generate.py [--out DIR]

Run from the repository root. Idempotent: the same docs always produce
byte-identical output, sorted by feature then id. `--out` writes into another
directory instead of docs/_generated/ (check.py uses it to detect stale files).

This module also holds the parsing shared with check.py.

Frontmatter parser limits (no YAML dependency in this repo):
- the block is the lines between a first line `---` and the next `---`;
- each line is `key: value`; nested maps, multi-line values and block lists
  (`- item`) are not supported;
- a value is either a scalar or an inline list `[a, b]`; list items cannot
  contain commas or brackets;
- one pair of surrounding single or double quotes is stripped from a scalar;
- `#` comments are NOT stripped — `status: active  # x` reads as `active  # x`.

open-questions.md collects every line containing "OPEN QUESTION" outside
docs/_generated/, except inside ``` fences or `inline code`.
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

from mdparse import (  # noqa: F401 — re-exported: check.py and the tests use g.<name>
    h2_sections,
    iter_unfenced,
    parse_scalar,
    parse_value,
    split_frontmatter,
)
import specdocs

ROOT = Path.cwd()
DOCS = ROOT / "docs"
GENERATED = DOCS / "_generated"
GENERATED_HEADER = "<!-- GENERATED by tools/docs/generate.py — DO NOT EDIT -->"

# Folder name → id DOMAIN, only where the two differ; otherwise DOMAIN is the
# folder name upper-cased with `-` removed. Ids were kept from the object
# codes of the previous docs layout; ids are permanent (docs/README.md).
DOMAIN_OVERRIDES = {
    "study-mode": "MODE",
    "tags": "TAG",
    "starter-decks": "STARTER",
    "reminders": "REMINDER",
}
SHARED_RULE_DOMAIN = "CORE"
SHARED = "shared"

TEST_DIRS = ("test", "integration_test")
TEST_SUFFIXES = (".dart",)

OPEN_QUESTION = "OPEN QUESTION"
# Mentions inside ``` fences or `inline code` describe the marker, not a question.
INLINE_CODE = re.compile(r"`[^`]*`")


@dataclass
class Doc:
    path: Path
    kind: str  # "BR" | "UC" | "ADR" | "FEATURE" | "FN" | "SCR"
    feature: str  # feature folder name, or SHARED
    meta: dict[str, object]
    body: str
    frontmatter_error: str | None = None
    sections: list[str] = field(default_factory=list)
    line: int = 0  # heading line of a section document; 0 for a file document
    screen: object = None  # specdocs.Screen for kind "SCR"

    @property
    def is_section(self) -> bool:
        return self.line > 0

    @property
    def id(self) -> str:
        return str(self.meta.get("id", ""))

    @property
    def title(self) -> str:
        return str(self.meta.get("title", ""))

    @property
    def status(self) -> str:
        return str(self.meta.get("status", ""))

    def as_list(self, key: str) -> list[str]:
        value = self.meta.get(key)
        if isinstance(value, list):
            return value
        return []


# ---------------------------------------------------------------- parsing


def classify(path: Path) -> tuple[str, str] | None:
    """Return (kind, feature) for a structured doc, None for free-form docs."""
    parts = path.relative_to(DOCS).parts
    if len(parts) == 3 and parts[0] == SHARED and parts[1] == "rules":
        return "BR", SHARED
    if len(parts) == 3 and parts[0] == SHARED and parts[1] == "decisions":
        return "ADR", SHARED
    if len(parts) == 3 and parts[0] == "features" and parts[2] == "README.md":
        return "FEATURE", parts[1]
    if len(parts) == 4 and parts[0] == "features" and parts[2] == "rules":
        return "BR", parts[1]
    if len(parts) == 4 and parts[0] == "features" and parts[2] == "usecases":
        return "UC", parts[1]
    if len(parts) == 3 and parts[0] == "screens" and parts[1] == "spec":
        return "SCR", ""
    return None


def load_file_docs() -> list[Doc]:
    docs: list[Doc] = []
    for path in sorted(DOCS.rglob("*.md")):
        kind_feature = classify(path)
        if kind_feature is None:
            continue
        kind, feature = kind_feature
        text = path.read_text(encoding="utf-8")
        meta, body, error = split_frontmatter(text)
        doc = Doc(
            path=path,
            kind=kind,
            feature=feature,
            meta=meta or {},
            body=body,
            frontmatter_error=error if meta is not None else (error or "missing frontmatter"),
            sections=h2_sections(body),
        )
        if kind == "SCR":
            doc.feature = str(doc.meta.get("domain", ""))
            offset = len(text.splitlines()) - len(body.splitlines())
            doc.screen = specdocs.parse_screen(body, offset)
        docs.append(doc)
    return docs


def use_cases_file() -> Path:
    return DOCS / "USE_CASES.md"


def functional_spec_dir() -> Path:
    return DOCS / "functional-spec"


def screen_catalog_file() -> Path:
    return DOCS / "screens" / "SCREEN_CATALOG.md"


def navigation_file() -> Path:
    return DOCS / "NAVIGATION.md"


def feature_of_domain(doc_id: str) -> str:
    """`UC-DECK-001` → `deck`; "" when no feature folder has that DOMAIN."""
    parts = doc_id.split("-")
    domain = parts[1] if len(parts) == 3 else ""
    return {domain_of(name): name for name in feature_names()}.get(domain, "")


def section_doc(path: Path, kind: str, feature: str, section: specdocs.Section) -> Doc:
    return Doc(
        path=path,
        kind=kind,
        feature=feature,
        meta=section.meta,
        body=section.body,
        frontmatter_error=section.error,
        sections=section.subsections,
        line=section.line,
    )


def load_section_docs() -> list[Doc]:
    docs: list[Doc] = []
    if use_cases_file().exists():
        text = use_cases_file().read_text(encoding="utf-8")
        for section in specdocs.use_case_sections(text):
            docs.append(section_doc(use_cases_file(), "UC", feature_of_domain(section.id), section))
    if functional_spec_dir().is_dir():
        for path in sorted(functional_spec_dir().glob("*.md")):
            if path.name == "README.md":
                continue
            for section in specdocs.function_sections(path.read_text(encoding="utf-8")):
                docs.append(section_doc(path, "FN", path.stem, section))
    return docs


def load_all() -> tuple[list[Doc], list[Doc]]:
    """(documents, migrated): a legacy UC file whose id USE_CASES.md now defines
    is returned apart; the section is the definition (plan PT6, until Task 44)."""
    files = load_file_docs()
    sections = load_section_docs()
    moved = {doc.id for doc in sections if doc.kind == "UC"}
    migrated = [doc for doc in files if doc.kind == "UC" and doc.id in moved]
    migrated_paths = {doc.path for doc in migrated}
    return [doc for doc in files if doc.path not in migrated_paths] + sections, migrated


def load_docs() -> list[Doc]:
    return load_all()[0]


def domain_of(feature: str) -> str:
    if feature == SHARED:
        return SHARED_RULE_DOMAIN
    return DOMAIN_OVERRIDES.get(feature, feature.upper().replace("-", ""))


def feature_names() -> list[str]:
    root = DOCS / "features"
    if not root.is_dir():
        return []
    return sorted(p.name for p in root.iterdir() if p.is_dir())


def rel_link(target: Path, from_dir: Path) -> str:
    return Path(os.path.relpath(target, from_dir)).as_posix()


def cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip() or "—"


# ------------------------------------------------------------ derivations


def used_by(docs: list[Doc]) -> dict[str, list[str]]:
    """BR id → ids of the FNs (and legacy UC files) whose `rules` cite it."""
    usage: dict[str, set[str]] = {}
    for doc in docs:
        if doc.kind == "FN" or (doc.kind == "UC" and not doc.is_section):
            for rule_id in doc.as_list("rules"):
                usage.setdefault(rule_id, set()).add(doc.id)
    return {rule_id: sorted(users) for rule_id, users in usage.items()}


def invoked_by(docs: list[Doc]) -> dict[str, list[str]]:
    """FN id → ids of the UC sections and screens that invoke it."""
    usage: dict[str, set[str]] = {}
    for doc in docs:
        if doc.kind == "UC" and doc.is_section:
            targets = doc.as_list("invokes")
        elif doc.kind == "SCR" and doc.screen is not None:
            targets = doc.screen.invokes
        else:
            continue
        for fn_id in targets:
            usage.setdefault(fn_id, set()).add(doc.id)
    return {fn_id: sorted(users) for fn_id, users in usage.items()}


def test_files() -> list[Path]:
    files: list[Path] = []
    for name in TEST_DIRS:
        root = ROOT / name
        if not root.is_dir():
            continue
        files += [p for p in root.rglob("*") if p.is_file() and p.suffix in TEST_SUFFIXES]
    return sorted(files)


def golden_files() -> dict[str, Path]:
    """Golden PNG name → path, for every PNG under test/**/goldens/."""
    root = ROOT / "test"
    if not root.is_dir():
        return {}
    return {path.name: path for path in sorted(root.rglob("*.png")) if "goldens" in path.parts}


def tests_by_id(ids: list[str]) -> dict[str, list[str]]:
    found: dict[str, list[str]] = {doc_id: [] for doc_id in ids}
    for path in test_files():
        text = path.read_text(encoding="utf-8", errors="replace")
        for doc_id in ids:
            if doc_id in text:
                found[doc_id].append(path.relative_to(ROOT).as_posix())
    return found


def group_order(docs: list[Doc]) -> list[str]:
    features = sorted({d.feature for d in docs if d.feature != SHARED} | set(feature_names()))
    return [SHARED] + features


# ------------------------------------------------------------- rendering


def render_index(docs: list[Doc]) -> str:
    usage = used_by(docs)
    invoked = invoked_by(docs)
    lines = [GENERATED_HEADER, "", "# Index", ""]
    by_id = lambda d: d.id  # noqa: E731
    for group in group_order(docs):
        group_docs = [d for d in docs if d.feature == group]
        readme = next((d for d in group_docs if d.kind == "FEATURE"), None)
        title = f"[{group}]({rel_link(readme.path, GENERATED)})" if readme else group
        lines += [f"## {title}", ""]
        rules = sorted((d for d in group_docs if d.kind == "BR"), key=by_id)
        cases = sorted((d for d in group_docs if d.kind == "UC"), key=by_id)
        decisions = sorted((d for d in group_docs if d.kind == "ADR"), key=by_id)
        functions = sorted((d for d in group_docs if d.kind == "FN"), key=by_id)
        screens = sorted((d for d in group_docs if d.kind == "SCR"), key=by_id)
        if not (rules or cases or decisions or functions or screens):
            lines += ["Chưa có tài liệu.", ""]
            continue
        if rules:
            lines += ["### Rules", "", "| ID | Title | Status | Summary | Used by |", "|---|---|---|---|---|"]
            for d in rules:
                users = ", ".join(usage.get(d.id, [])) or "—"
                lines.append(
                    f"| [{d.id}]({rel_link(d.path, GENERATED)}) | {cell(d.title)} | {cell(d.status)} "
                    f"| {cell(str(d.meta.get('summary', '')))} | {users} |"
                )
            lines.append("")
        if functions:
            lines += ["### Functions", "", "| ID | Title | Status | Invoked by |", "|---|---|---|---|"]
            for d in functions:
                lines.append(
                    f"| [{d.id}]({rel_link(d.path, GENERATED)}) | {cell(d.title)} | {cell(d.status)} "
                    f"| {', '.join(invoked.get(d.id, [])) or '—'} |"
                )
            lines.append("")
        for heading, items in (("Use cases", cases), ("Decisions", decisions)):
            if not items:
                continue
            lines += [f"### {heading}", "", "| ID | Title | Status | Summary |", "|---|---|---|---|"]
            for d in items:
                lines.append(
                    f"| [{d.id}]({rel_link(d.path, GENERATED)}) | {cell(d.title)} | {cell(d.status)} "
                    f"| {cell(str(d.meta.get('summary', '')))} |"
                )
            lines.append("")
        if screens:
            lines += ["### Screens", "", "| ID | Name | Status | Route |", "|---|---|---|---|"]
            for d in screens:
                routes = ", ".join(f"`{route}`" for route in d.as_list("route"))
                lines.append(
                    f"| [{d.id}]({rel_link(d.path, GENERATED)}) | {cell(str(d.meta.get('name', '')))} "
                    f"| {cell(d.status)} | {routes or '—'} |"
                )
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_traceability(docs: list[Doc]) -> str:
    cases = sorted((d for d in docs if d.kind == "UC"), key=lambda d: (d.feature, d.id))
    functions = {d.id: d for d in docs if d.kind == "FN"}
    tests = tests_by_id([d.id for d in cases])
    lines = [
        GENERATED_HEADER,
        "",
        "# Traceability",
        "",
        "Use case → functions → rules → code → test. Test = file trong "
        + ", ".join(f"`{name}/`" for name in TEST_DIRS)
        + " có chứa chuỗi ID của UC.",
        "",
        "| UC | Status | Functions | Rules | Code | Tests |",
        "|---|---|---|---|---|---|",
    ]
    for d in cases:
        invoked = [functions[f] for f in d.as_list("invokes") if f in functions]
        rules = d.as_list("rules") if not d.is_section else sorted({r for f in invoked for r in f.as_list("rules")})
        code = list(dict.fromkeys(d.as_list("code") + [c for f in invoked for c in f.as_list("code")]))
        lines.append(
            f"| [{d.id}]({rel_link(d.path, GENERATED)}) | {cell(d.status)} "
            f"| {cell(', '.join(d.as_list('invokes')))} "
            f"| {cell(', '.join(rules))} "
            f"| {cell(', '.join(f'`{c}`' for c in code))} "
            f"| {cell(', '.join(f'`{t}`' for t in tests[d.id]))} |"
        )
    if not cases:
        lines.append("| — | — | — | — | — | — |")
    return "\n".join(lines) + "\n"


def router_entries() -> list[str]:
    path = navigation_file()
    return specdocs.ids_in(path.read_text(encoding="utf-8"), "SCR") if path.exists() else []


def render_screens(docs: list[Doc]) -> str:
    screens = sorted((d for d in docs if d.kind == "SCR" and d.screen is not None), key=lambda d: d.id)
    functions = {d.id: d for d in docs if d.kind == "FN"}
    incoming: dict[str, set[str]] = {}
    for doc in screens:
        for target in doc.screen.navigates:
            incoming.setdefault(target, set()).add(doc.id)
    routed = router_entries()
    goldens = golden_files()
    lines = [GENERATED_HEADER, "", "# Screens", ""]
    if not screens:
        lines += ["Không có.", ""]
    for doc in screens:
        rules = sorted({r for f in doc.screen.invokes if f in functions for r in functions[f].as_list("rules")})
        entries = sorted(incoming.get(doc.id, set())) + (["NAVIGATION.md"] if doc.id in routed else [])
        lines += [
            f"## [{doc.id}]({rel_link(doc.path, GENERATED)}) · {cell(str(doc.meta.get('name', '')))}",
            "",
            f"- Invokes: {', '.join(doc.screen.invokes) or '—'}",
            f"- Rules via FN: {', '.join(rules) or '—'}",
            f"- Use cases: {', '.join(doc.screen.related_ucs) or '—'}",
            f"- Entry points: {', '.join(entries) or '—'}",
            "",
        ]
        states = [s for s in doc.screen.states if s.key and not s.removed]
        if states:
            lines += ["| State | Golden | Present |", "|---|---|---|"]
            for state in states:
                names = [specdocs.golden_name(doc.id, state.key, v) for v in state.variants]
                present = ", ".join(f"`{n}`" for n in names if n in goldens) or "—"
                lines.append(f"| `{state.key}` | {', '.join(state.variants) or 'none'} | {present} |")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_navigation(docs: list[Doc]) -> str:
    screens = [d for d in docs if d.kind == "SCR" and d.screen is not None]
    edges = sorted({(d.id, target) for d in screens for target in d.screen.navigates})
    lines = [
        GENERATED_HEADER,
        "",
        "# Navigation graph",
        "",
        "Screen → screen edges from each spec's `Navigate to:` lines (spec R9).",
        "",
        "| From | To |",
        "|---|---|",
    ]
    lines += [f"| {source} | {target} |" for source, target in edges] or ["| — | — |"]
    lines += ["", "## Router entries", "", "Screens that `NAVIGATION.md` routes to.", ""]
    lines += [f"- {doc_id}" for doc_id in sorted(router_entries())] or ["Không có."]
    return "\n".join(lines) + "\n"


def render_open_questions() -> str:
    lines = [GENERATED_HEADER, "", "# Open questions", ""]
    count = 0
    for path in sorted(DOCS.rglob("*.md")):
        if GENERATED in path.parents:
            continue
        hits = [
            (line_no, line.strip())
            for line_no, line in iter_unfenced(path.read_text(encoding="utf-8"))
            if OPEN_QUESTION in INLINE_CODE.sub("", line)
        ]
        if not hits:
            continue
        link = rel_link(path, GENERATED)
        lines += [f"## [{path.relative_to(DOCS).as_posix()}]({link})", ""]
        for line_no, text in hits:
            lines.append(f"- L{line_no}: {rebase_links(text, path.parent, GENERATED)}")
            count += 1
        lines.append("")
    if count == 0:
        lines += ["Không có.", ""]
    return "\n".join(lines).rstrip() + "\n"


MD_LINK = re.compile(r"(\[[^\]]*\]\()([^)\s]+)(\))")


def rebase_links(text: str, from_dir: Path, to_dir: Path) -> str:
    """Rewrite relative markdown links so they still resolve from to_dir."""

    def fix(match: re.Match[str]) -> str:
        target = match[2]
        if re.match(r"^[a-z][a-z0-9+.-]*:", target, re.I) or target.startswith("#"):
            return match[0]
        file_part, _, anchor = target.partition("#")
        moved = rel_link(from_dir / file_part, to_dir) + (f"#{anchor}" if anchor else "")
        return f"{match[1]}{moved}{match[3]}"

    return MD_LINK.sub(fix, text)


def render_all() -> dict[str, str]:
    docs = load_docs()
    return {
        "index.md": render_index(docs),
        "traceability.md": render_traceability(docs),
        "screens.md": render_screens(docs),
        "navigation-graph.md": render_navigation(docs),
        "open-questions.md": render_open_questions(),
    }


def write_all(out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, content in render_all().items():
        (out_dir / name).write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=GENERATED, help="output directory (default: docs/_generated)")
    args = parser.parse_args()
    if not DOCS.is_dir():
        print("ERROR docs: not found — run from the repository root")
        return 1
    files = render_all()
    args.out.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        (args.out / name).write_text(content, encoding="utf-8", newline="\n")
    shown = args.out.relative_to(ROOT) if args.out.is_relative_to(ROOT) else args.out
    print(f"OK {shown}: generated {len(files)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
