#!/usr/bin/env python3
"""Split the MemoX V3 Flutter handoff JSON into Markdown, deterministically.

    python tools/docs/split_handoff.py [<handoff.json> [<output-dir>]]

Run from the repository root. The defaults are docs/shared/ui/design-handoff.json
and docs/shared/ui/design-handoff/; tools/docs/check.py compares that folder with
a fresh split (find_drift), the way it does for docs/_generated/.

Every file opens with a GENERATED marker line and a blank line. After that, each
"spec" string is written byte-for-byte: no trimming, no added newline. Everything
else (index, traceability) is derived from the JSON with no timestamps, so the
same JSON always produces the same bytes.

Re-running is safe. A manifest records the SHA-256 of every file written.
Unchanged files are left untouched and files the new JSON no longer produces are
removed, but the run stops before writing anything (exit 1) when it would
overwrite or remove a file that is not what the last run wrote: a hand edit, or
a file the script never wrote. Bad input exits 2.

Outputs:
    00-index.md                   widget / section / action / runnableAfter / composition / file
    01-foundations.md             $.foundations.spec
    02-theme-binding.md           $.themeHandoff.spec
    widgets/<kebab>.md            $.widgets[i].spec, named from $.widgets[i].name
    99-traceability.md            every output -> its source JSON path
    .handoff-split-manifest.json  output path -> SHA-256 of the bytes written
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path.cwd()
DEFAULT_INPUT = ROOT / "docs" / "shared" / "ui" / "design-handoff.json"
DEFAULT_OUTPUT = ROOT / "docs" / "shared" / "ui" / "design-handoff"

INDEX_FILE = "00-index.md"
FOUNDATIONS_FILE = "01-foundations.md"
THEME_FILE = "02-theme-binding.md"
TRACE_FILE = "99-traceability.md"
WIDGETS_DIR = "widgets"
MANIFEST_FILE = ".handoff-split-manifest.json"
MARKER = "<!-- GENERATED by tools/docs/split_handoff.py from {input} — DO NOT EDIT -->"
EMPTY = "—"


class SplitError(Exception):
    """The JSON does not have the shape this script relies on."""


class ConflictError(Exception):
    """The output dir holds files this run must neither overwrite nor remove."""

    def __init__(self, conflicts: list[str]) -> None:
        super().__init__("\n".join(conflicts))
        self.conflicts = conflicts


@dataclass(frozen=True)
class Output:
    path: str  # relative to the output dir, always "/"-separated
    body: str  # the file after its marker; for "verbatim", exactly the JSON string
    source: str  # JSON path(s) this file comes from
    kind: str  # "verbatim" | "derived"
    note: str = ""


def kebab(name: str) -> str:
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", name)
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", s)
    s = re.sub(r"[^A-Za-z0-9]+", "-", s).strip("-").lower()
    if not s:
        raise SplitError(f"cannot derive a file name from widget name {name!r}")
    return s


def _dig(node, *keys, default=None):
    for key in keys:
        if not isinstance(node, dict) or key not in node:
            return default
        node = node[key]
    return node


def _spec(node, json_path: str) -> str:
    if not isinstance(node, str) or not node:
        raise SplitError(f"{json_path} must be a non-empty string")
    return node


def _cell(value) -> str:
    if value is None or value == "":
        return EMPTY
    return str(value).replace("|", "\\|").replace("\r", " ").replace("\n", " ")


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _widget_outputs(data: dict) -> list[tuple[Output, dict]]:
    widgets = data.get("widgets")
    if not isinstance(widgets, list):
        raise SplitError("$.widgets must be a list")
    seen: dict[str, str] = {}
    result = []
    for i, w in enumerate(widgets):
        where = f"$.widgets[{i}]"
        if not isinstance(w, dict) or not isinstance(w.get("name"), str):
            raise SplitError(f"{where}.name must be a string")
        name = w["name"]
        path = f"{WIDGETS_DIR}/{kebab(name)}.md"
        if path in seen:
            raise SplitError(f"{where} ({name!r}) and {seen[path]} both map to {path}")
        seen[path] = f"{where} ({name!r})"
        output = Output(
            path, _spec(w.get("spec"), f"{where}.spec"), f"{where}.spec", "verbatim", name
        )
        result.append((output, w))
    return result


def _build_index(data: dict, input_name: str, docs: list[Output],
                 widgets: list[tuple[Output, dict]]) -> str:
    composition = _dig(data, "themeHandoff", "views", "componentComposition", default={})
    order = _dig(data, "implementationOrder", default=[])
    lines = [
        "# MemoX V3 handoff — index",
        "",
        f"> Generated by `tools/docs/split_handoff.py` from `{input_name}`. Do not edit by "
        "hand: change the JSON and run `python tools/docs/split_handoff.py` from the "
        f"repository root. Input SHA-256 and the source of every file: [{TRACE_FILE}]({TRACE_FILE}).",
        "",
        f"- JSON `generated`: {_cell(data.get('generated'))}",
        f"- JSON `source`: {_cell(data.get('source'))}",
        f"- JSON `contract`: {_cell(data.get('contract'))}",
        "- Run order (`implementationOrder`): "
        + (" → ".join(map(str, order)) if order else EMPTY),
        "",
        "## Usage (verbatim from JSON `usage`)",
        "",
        f"> {_cell(data.get('usage'))}",
        "",
        "## Documents",
        "",
        "| Document | Step | Mode / kind | Runnable after | File |",
        "|---|---|---|---|---|",
    ]
    for output, name, step, mode in (
        (docs[0], "Foundations", _dig(data, "foundations", "step"),
         _dig(data, "foundations", "handoffMode")),
        (docs[1], "Theme binding", _dig(data, "themeHandoff", "step"),
         _dig(data, "themeHandoff", "kind")),
    ):
        lines.append(
            f"| {name} | {_cell(step)} | {_cell(mode)} | {EMPTY} "
            f"| [{output.path}]({output.path}) |"
        )
    lines += [
        "",
        f"## Widgets ({len(widgets)})",
        "",
        "Composition comes from `$.themeHandoff.views.componentComposition`; "
        f"`{EMPTY}` means the JSON lists none.",
        "",
        "| Widget | Section | Action | Runnable after | Composition | File |",
        "|---|---|---|---|---|---|",
    ]
    for output, w in widgets:
        parts = composition.get(w["name"]) if isinstance(composition, dict) else None
        composes = "<br>".join(_cell(p) for p in parts) if parts else EMPTY
        lines.append(
            f"| {_cell(w['name'])} | {_cell(w.get('section'))} "
            f"| {_cell(w.get('implementationAction'))} | {_cell(w.get('runnableAfter'))} "
            f"| {composes} | [{output.path}]({output.path}) |"
        )
    return "\n".join(lines) + "\n"


def _build_trace(input_name: str, input_sha: str, outputs: list[Output]) -> str:
    lines = [
        "# MemoX V3 handoff — traceability",
        "",
        f"> Generated by `tools/docs/split_handoff.py`. Input `{input_name}` "
        f"(SHA-256 `{input_sha}`).",
        "> Every file opens with a GENERATED marker and a blank line. What follows is "
        "exactly the JSON string for `verbatim` files, so SHA-256 and chars (of that part) "
        "match it; `derived` files are built from the listed paths.",
        "",
        "| Output | Kind | Source JSON path | Widget | SHA-256 | Chars |",
        "|---|---|---|---|---|---|",
    ]
    for o in outputs:
        lines.append(
            f"| [{o.path}]({o.path}) | {o.kind} | `{o.source}` | {_cell(o.note)} "
            f"| `{_sha(o.body.encode('utf-8'))}` | {len(o.body)} |"
        )
    lines.append(
        f"| {TRACE_FILE} | derived | all of the above | {EMPTY} | {EMPTY} | {EMPTY} |"
    )
    return "\n".join(lines) + "\n"


def build_outputs(data, input_name: str, input_sha: str) -> list[Output]:
    if not isinstance(data, dict):
        raise SplitError("top-level JSON value must be an object")
    docs = [
        Output(FOUNDATIONS_FILE,
               _spec(_dig(data, "foundations", "spec"), "$.foundations.spec"),
               "$.foundations.spec", "verbatim"),
        Output(THEME_FILE,
               _spec(_dig(data, "themeHandoff", "spec"), "$.themeHandoff.spec"),
               "$.themeHandoff.spec", "verbatim"),
    ]
    widgets = _widget_outputs(data)
    index = Output(
        INDEX_FILE,
        _build_index(data, input_name, docs, widgets),
        "$.generated, $.source, $.contract, $.usage, $.implementationOrder, "
        "$.foundations.{step,handoffMode}, $.themeHandoff.{step,kind}, "
        "$.widgets[*].{name,section,implementationAction,runnableAfter}, "
        "$.themeHandoff.views.componentComposition",
        "derived",
    )
    outputs = [index, *docs, *(o for o, _ in widgets)]
    trace = Output(
        TRACE_FILE,
        _build_trace(input_name, input_sha, outputs),
        "all outputs above",
        "derived",
    )
    return [*outputs, trace]


def render_files(data, input_name: str, input_sha: str) -> dict[str, bytes]:
    """Output path -> file bytes: the GENERATED marker, a blank line, then the body.

    Bytes, so no newline translation happens on Windows.
    """
    marker = MARKER.format(input=input_name)
    return {
        o.path: f"{marker}\n\n{o.body}".encode("utf-8")
        for o in build_outputs(data, input_name, input_sha)
    }


def load_files(input_path: Path) -> dict[str, bytes]:
    """render_files for a JSON file; raises OSError, ValueError or SplitError."""
    raw = input_path.read_bytes()
    data = json.loads(raw.decode("utf-8-sig"))
    return render_files(data, input_path.name, _sha(raw))


def read_manifest(out_dir: Path) -> dict[str, str]:
    """Path -> SHA-256 of the bytes the last run wrote there; {} when there is none."""
    try:
        recorded = json.loads((out_dir / MANIFEST_FILE).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return recorded if isinstance(recorded, dict) else {}


def manifest_bytes(files: dict[str, bytes]) -> bytes:
    recorded = {path: _sha(data) for path, data in sorted(files.items())}
    return (json.dumps(recorded, indent=2) + "\n").encode("utf-8")


def find_conflicts(out_dir: Path, files: dict[str, bytes]) -> list[str]:
    """Files a run would overwrite or remove although they are not what the last
    run wrote: edits made by hand, or files this script never wrote."""
    recorded = read_manifest(out_dir)
    conflicts = []
    for path in sorted(files.keys() | recorded.keys()):
        target = out_dir / path
        if not target.is_file():
            continue
        current = target.read_bytes()
        if current == files.get(path):
            continue
        if path not in recorded:
            conflicts.append(f"{path}: not written by this script")
        elif _sha(current) != recorded[path]:
            conflicts.append(f"{path}: edited since the last run")
    return conflicts


def find_drift(out_dir: Path, files: dict[str, bytes]) -> list[tuple[str, str]]:
    """(path, "missing" | "changed" | "extra") for every file in out_dir that is not
    exactly what a run would leave there, manifest included. Writes nothing."""
    expected = {**files, MANIFEST_FILE: manifest_bytes(files)}
    present: set[str] = set()
    if out_dir.is_dir():
        present = {p.relative_to(out_dir).as_posix() for p in out_dir.rglob("*") if p.is_file()}
    drift = []
    for path in sorted(expected.keys() | present):
        if path not in present:
            drift.append((path, "missing"))
        elif path not in expected:
            drift.append((path, "extra"))
        elif (out_dir / path).read_bytes() != expected[path]:
            drift.append((path, "changed"))
    return drift


def write_outputs(out_dir: Path, files: dict[str, bytes]) -> tuple[int, int, int]:
    """Write changed files and remove those the last run wrote that this one does not.

    Raises ConflictError before touching anything when that would overwrite or
    remove a file that is not what the last run wrote.
    """
    conflicts = find_conflicts(out_dir, files)
    if conflicts:
        raise ConflictError(conflicts)
    previous = read_manifest(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    written = unchanged = 0
    for path, data in files.items():
        target = out_dir / path
        if target.is_file() and target.read_bytes() == data:
            unchanged += 1
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        written += 1

    removed = 0
    root = out_dir.resolve()
    for rel in sorted(previous.keys() - files.keys()):
        target = (out_dir / rel).resolve()
        if root in target.parents and target.is_file():
            target.unlink()
            removed += 1
            try:
                target.parent.rmdir()  # only succeeds when empty
            except OSError:
                pass

    manifest = out_dir / MANIFEST_FILE
    expected = manifest_bytes(files)
    if not manifest.is_file() or manifest.read_bytes() != expected:
        manifest.write_bytes(expected)
    return written, unchanged, removed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Split the MemoX V3 handoff JSON into Markdown.")
    parser.add_argument("input", type=Path, nargs="?", default=DEFAULT_INPUT,
                        help="handoff JSON file (default: %(default)s)")
    parser.add_argument("output_dir", type=Path, nargs="?", default=DEFAULT_OUTPUT,
                        help="directory to (re)generate (default: %(default)s)")
    args = parser.parse_args(argv)

    try:
        files = load_files(args.input)
    except (OSError, ValueError, SplitError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    try:
        written, unchanged, removed = write_outputs(args.output_dir, files)
    except ConflictError as error:
        print(
            f"error: nothing written; {len(error.conflicts)} file(s) in {args.output_dir} "
            "are not what this script last wrote:",
            file=sys.stderr,
        )
        for conflict in error.conflicts:
            print(f"  {conflict}", file=sys.stderr)
        print(
            "Move any edit worth keeping out of this folder, restore (git checkout) or "
            "delete these files, then run again.",
            file=sys.stderr,
        )
        return 1
    print(f"{len(files)} files: {written} written, {unchanged} unchanged, {removed} removed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
