"""Configuration key constants."""

class ConfigKeys:
    """Configuration key names used across the guard."""
    VERSION = "version"
    METADATA = "metadata"
    NAME = "name"
    DESCRIPTION = "description"
    PROFILE = "profile"
    PROFILES = "profiles"
    SCOPES = "scopes"
    SCOPE = "scope"
    FIX = "fix"
    HINT = "hint"
    TAGS = "tags"
    EXAMPLE_BAD = "example_bad"
    EXAMPLE_GOOD = "example_good"

    PROJECT = "project"
    PROJECT_NAME = "name"
    PROJECT_ROOT = "root"
    SOURCE_ROOTS = "source_roots"

    RULE_SETS = "rule_sets"
    COMMON = "common"
    LANGUAGES = "languages"
    PROJECTS = "projects"
    REGISTRIES = "registries"
    CONFIG = "config"
    RULESET = "ruleset"

    RULES = "rules"
    ID = "id"
    TYPE = "type"
    MODE = "mode"
    ENABLED = "enabled"
    SEVERITY = "severity"
    MESSAGE = "message"
    INCLUDE = "include"
    EXCLUDE = "exclude"
    PATTERNS = "patterns"
    PATTERN = "pattern"
    COMMENT_PREFIXES = "comment_prefixes"
    NODE_TYPES = "node_types"
    CHECK = "check"
    WIDGET_BASE_CLASSES = "widget_base_classes"
    STATE_FIELD_NAMES = "state_field_names"
    VARIANT_FIELD_NAMES = "variant_field_names"
    ALLOWED_VALUES = "allowed_values"
    KNOWN_CONTRACTS = "known_contracts"
    ONLY_CATEGORIES = "only_categories"
    MAX_LINES = "max_lines"
    COUNT_MODE = "count_mode"

    OVERRIDES = "overrides"
    DISABLED_RULES = "disabled_rules"
    RULE_OPTIONS = "rule_options"

    FAILURE = "failure"
    FAIL_ON = "fail_on"
    WARNING_AS_ERROR = "warning_as_error"

    REPORT = "report"
    FORMAT = "format"
    SHOW_CODE_LINE = "show_code_line"
    SHOW_FIX_HINT = "show_fix_hint"
