// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    deck,
    card,
    cardSchedule,
    tags,
    cardTags,
    reviewLog,
    appSettings,
    studySession,
    studyQueueItems,
    idxStudyQueuePending,
    studyGuessOptions,
    idxStudyGuessOptionsOption,
    idxCardScheduleDue,
    idxReviewLogCard,
    idxReviewLogSession,
    reviewLogAppendOnly,
    reviewLogNoDelete,
    idxTagsOwnerNameFolded,
    idxCardTagsTag,
    idxCardDeckCreated,
    idxDeckParentPosition,
    idxDeckRootPosition,
  ];
  late final Shape0 deck = Shape0(
    source: i0.VersionedTable(
      entityName: 'deck',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((parent_id IS NULL)=(root_id = id))',
        'CHECK(parent_id IS NOT NULL OR content_type = \'deck\')',
        'CHECK((parent_id IS NULL)=(scheduler_type IS NOT NULL))',
        'CHECK((parent_id IS NULL)=(generation IS NOT NULL))',
        'CHECK((parent_id IS NULL)=(scheduler_version IS NOT NULL))',
        'CHECK(parent_id IS NULL OR scheduler_config IS NULL)',
        'CHECK(parent_id IS NULL OR study_config IS NULL)',
        'CHECK(parent_id IS NULL OR generation IS NULL)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 card = Shape1(
    source: i0.VersionedTable(
      entityName: 'card',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_15,
        _column_17,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 cardSchedule = Shape2(
    source: i0.VersionedTable(
      entityName: 'card_schedule',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((scheduler_type = \'eight_box\')=(current_box IS NOT NULL))',
        'CHECK((scheduler_type = \'sm2\')=(ease_factor IS NOT NULL))',
        'CHECK((ease_factor IS NULL)=(interval_days IS NULL))',
        'CHECK((ease_factor IS NULL)=(repetitions IS NULL))',
        'CHECK(learned_at IS NOT NULL OR due_at IS NULL)',
      ],
      columns: [
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 tags = Shape3(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_41, _column_6, _column_17],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 cardTags = Shape4(
    source: i0.VersionedTable(
      entityName: 'card_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(card_id, tag_id)'],
      columns: [_column_42, _column_43],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 reviewLog = Shape5(
    source: i0.VersionedTable(
      entityName: 'review_log',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(mode = \'fill\' OR(comparison_version IS NULL AND used_hint IS NULL))',
        'CHECK(outcome_reason IS NULL OR mode = \'recall\')',
      ],
      columns: [
        _column_0,
        _column_42,
        _column_44,
        _column_29,
        _column_31,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 appSettings = Shape6(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 studySession = Shape7(
    source: i0.VersionedTable(
      entityName: 'study_session',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((status IN (\'in_progress\', \'completed\') AND end_reason IS NULL)OR(status = \'abandoned\' AND end_reason IN (\'user_exit\', \'interrupted\'))OR(status = \'invalidated\' AND end_reason IN (\'scheduler_reset\', \'scheduler_changed\', \'stale_generation\', \'content_deleted\'))OR(status = \'failed\' AND end_reason = \'persistence_error\'))',
        'CHECK((status = \'in_progress\')=(ended_at IS NULL))',
        'CHECK(direction IS NULL OR(session_kind = \'reviewing\' AND current_mode = \'self_assess\'))',
      ],
      columns: [
        _column_0,
        _column_19,
        _column_3,
        _column_31,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_61,
        _column_73,
        _column_74,
        _column_75,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 studyQueueItems = Shape8(
    source: i0.VersionedTable(
      entityName: 'study_queue_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(session_id, mode, round, card_id)',
        'CHECK(mode <> \'self_assess\' OR answers_in_session <= 4)',
        'CHECK(mode = \'recall\' OR(remaining_ms IS NULL AND is_revealed = 0))',
        'CHECK(mode = \'self_assess\' OR direction IS NULL)',
      ],
      columns: [
        _column_76,
        _column_46,
        _column_77,
        _column_42,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_83,
        _column_50,
        _column_84,
        _column_85,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxStudyQueuePending = i1.Index(
    'idx_study_queue_pending',
    'CREATE INDEX idx_study_queue_pending ON study_queue_items (session_id, status, available_at, position)',
  );
  late final Shape9 studyGuessOptions = Shape9(
    source: i0.VersionedTable(
      entityName: 'study_guess_options',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(session_id, mode, round, card_id, slot)',
        'UNIQUE(session_id, mode, round, card_id, option_card_id)',
        'FOREIGN KEY(session_id, mode, round, card_id)REFERENCES study_queue_items(session_id, mode, round, card_id)ON DELETE CASCADE',
      ],
      columns: [
        _column_44,
        _column_86,
        _column_87,
        _column_88,
        _column_89,
        _column_90,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxStudyGuessOptionsOption = i1.Index(
    'idx_study_guess_options_option',
    'CREATE INDEX idx_study_guess_options_option ON study_guess_options (option_card_id)',
  );
  final i1.Index idxCardScheduleDue = i1.Index(
    'idx_card_schedule_due',
    'CREATE INDEX idx_card_schedule_due ON card_schedule (due_at)',
  );
  final i1.Index idxReviewLogCard = i1.Index(
    'idx_review_log_card',
    'CREATE INDEX idx_review_log_card ON review_log (card_id, answered_at)',
  );
  final i1.Index idxReviewLogSession = i1.Index(
    'idx_review_log_session',
    'CREATE INDEX idx_review_log_session ON review_log (session_id)',
  );
  final i1.Trigger reviewLogAppendOnly = i1.Trigger(
    'CREATE TRIGGER review_log_append_only BEFORE UPDATE ON review_log BEGIN SELECT RAISE (ABORT, \'review_log is append-only\');END',
    'review_log_append_only',
  );
  final i1.Trigger reviewLogNoDelete = i1.Trigger(
    'CREATE TRIGGER review_log_no_delete BEFORE DELETE ON review_log WHEN OLD.card_id IN (SELECT id FROM card) BEGIN SELECT RAISE (ABORT, \'review_log rows are only removed by a card cascade\');END',
    'review_log_no_delete',
  );
  final i1.Index idxTagsOwnerNameFolded = i1.Index(
    'idx_tags_owner_name_folded',
    'CREATE UNIQUE INDEX idx_tags_owner_name_folded ON tags (COALESCE(owner_id, \'\'), name_folded)',
  );
  final i1.Index idxCardTagsTag = i1.Index(
    'idx_card_tags_tag',
    'CREATE INDEX idx_card_tags_tag ON card_tags (tag_id, card_id)',
  );
  final i1.Index idxCardDeckCreated = i1.Index(
    'idx_card_deck_created',
    'CREATE INDEX idx_card_deck_created ON card (deck_id, created_at, id)',
  );
  final i1.Index idxDeckParentPosition = i1.Index(
    'idx_deck_parent_position',
    'CREATE INDEX idx_deck_parent_position ON deck (parent_id, sibling_position, id)',
  );
  final i1.Index idxDeckRootPosition = i1.Index(
    'idx_deck_root_position',
    'CREATE INDEX idx_deck_root_position ON deck (root_id, sibling_position, id)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get parentId =>
      columnsByName['parent_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rootId =>
      columnsByName['root_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get depth =>
      columnsByName['depth']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get contentType =>
      columnsByName['content_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ownerId =>
      columnsByName['owner_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get schedulerType =>
      columnsByName['scheduler_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get schedulerVersion =>
      columnsByName['scheduler_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get schedulerConfig =>
      columnsByName['scheduler_config']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get studyConfig =>
      columnsByName['study_config']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get generation =>
      columnsByName['generation']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get firstAnsweredAt =>
      columnsByName['first_answered_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sourceTemplateId =>
      columnsByName['source_template_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sourceTemplateVersion =>
      columnsByName['source_template_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get deleteBatchId =>
      columnsByName['delete_batch_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get siblingPosition =>
      columnsByName['sibling_position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'parent_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'REFERENCES deck(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'root_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'depth',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (depth BETWEEN 1 AND 10)',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'unset\' CHECK (content_type IN (\'unset\', \'card\', \'deck\'))',
      defaultValue: const i1.CustomExpression('\'unset\''),
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'owner_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scheduler_type',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (scheduler_type IN (\'eight_box\', \'sm2\'))',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'scheduler_version',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scheduler_config',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'study_config',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'generation',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'first_answered_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_template_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'source_template_version',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'delete_batch_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sibling_position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deckId =>
      columnsByName['deck_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get front =>
      columnsByName['front']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get back =>
      columnsByName['back']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get frontFolded =>
      columnsByName['front_folded']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get backFolded =>
      columnsByName['back_folded']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isFlagged =>
      columnsByName['is_flagged']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get example =>
      columnsByName['example']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get hint =>
      columnsByName['hint']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get pronunciation =>
      columnsByName['pronunciation']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deleteBatchId =>
      columnsByName['delete_batch_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'deck_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES deck(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'front',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'back',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'front_folded',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'back_folded',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_flagged',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_flagged IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'example',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hint',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'pronunciation',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get cardId =>
      columnsByName['card_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get schedulerType =>
      columnsByName['scheduler_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get schedulerVersion =>
      columnsByName['scheduler_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get generation =>
      columnsByName['generation']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get learnedAt =>
      columnsByName['learned_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dueAt =>
      columnsByName['due_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastAnsweredAt =>
      columnsByName['last_answered_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get answerCount =>
      columnsByName['answer_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lapseCount =>
      columnsByName['lapse_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get currentBox =>
      columnsByName['current_box']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get easeFactor =>
      columnsByName['ease_factor']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get intervalDays =>
      columnsByName['interval_days']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get repetitions =>
      columnsByName['repetitions']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'card_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL PRIMARY KEY REFERENCES card(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scheduler_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (scheduler_type IN (\'eight_box\', \'sm2\'))',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'scheduler_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'generation',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'learned_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'due_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_answered_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'answer_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'lapse_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'current_box',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'CHECK (current_box BETWEEN 1 AND 8)',
    );
i1.GeneratedColumn<double> _column_38(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'ease_factor',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'interval_days',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'repetitions',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameFolded =>
      columnsByName['name_folded']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ownerId =>
      columnsByName['owner_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name_folded',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get cardId =>
      columnsByName['card_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tagId =>
      columnsByName['tag_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'card_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES card(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tag_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES tags(id)ON DELETE CASCADE',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cardId =>
      columnsByName['card_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get schedulerType =>
      columnsByName['scheduler_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get generation =>
      columnsByName['generation']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mode =>
      columnsByName['mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get outcomeReason =>
      columnsByName['outcome_reason']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get comparisonVersion =>
      columnsByName['comparison_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get usedHint =>
      columnsByName['used_hint']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get direction =>
      columnsByName['direction']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get action =>
      columnsByName['action']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get answeredAt =>
      columnsByName['answered_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nextDueAt =>
      columnsByName['next_due_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get previousBox =>
      columnsByName['previous_box']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nextBox =>
      columnsByName['next_box']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get previousEaseFactor =>
      columnsByName['previous_ease_factor']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get nextEaseFactor =>
      columnsByName['next_ease_factor']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get previousIntervalDays =>
      columnsByName['previous_interval_days']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nextIntervalDays =>
      columnsByName['next_interval_days']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_45(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'kind',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (kind IN (\'learning\', \'scheduled\', \'relearning\'))',
);
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (mode IN (\'browse\', \'self_assess\', \'match\', \'guess\', \'recall\', \'fill\'))',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'outcome_reason',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'CHECK (outcome_reason IS NULL OR outcome_reason = \'timeout\')',
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'comparison_version',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'used_hint',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'CHECK (used_hint IS NULL OR used_hint IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'direction',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (direction IS NULL OR direction IN (\'korean_to_meaning\', \'meaning_to_korean\'))',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'action',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK ("action" IN (\'forgotten\', \'remembered\', \'again\', \'hard\', \'good\', \'easy\'))',
    );
i1.GeneratedColumn<int> _column_52(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'answered_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'next_due_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'previous_box',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_55(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'next_box',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<double> _column_56(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'previous_ease_factor',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: '',
    );
i1.GeneratedColumn<double> _column_57(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'next_ease_factor',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'previous_interval_days',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_59(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'next_interval_days',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cardLimit =>
      columnsByName['card_limit']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get newCardOrder =>
      columnsByName['new_card_order']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get themeMode =>
      columnsByName['theme_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get language =>
      columnsByName['language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get reminderEnabled =>
      columnsByName['reminder_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reminderMinuteOfDay =>
      columnsByName['reminder_minute_of_day']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reminderLastDeliveredAt =>
      columnsByName['reminder_last_delivered_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY CHECK (id = 1)',
    );
i1.GeneratedColumn<int> _column_61(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'card_limit',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 20',
      defaultValue: const i1.CustomExpression('20'),
    );
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'new_card_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'created\' CHECK (new_card_order IN (\'created\', \'random\'))',
      defaultValue: const i1.CustomExpression('\'created\''),
    );
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'theme_mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'system\' CHECK (theme_mode IN (\'system\', \'light\', \'dark\'))',
      defaultValue: const i1.CustomExpression('\'system\''),
    );
i1.GeneratedColumn<String> _column_64(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'language',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'system\' CHECK (language IN (\'system\', \'en\', \'vi\'))',
      defaultValue: const i1.CustomExpression('\'system\''),
    );
i1.GeneratedColumn<int> _column_65(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reminder_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (reminder_enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_66(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'reminder_minute_of_day',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT 1200 CHECK (reminder_minute_of_day BETWEEN 0 AND 1439)',
  defaultValue: const i1.CustomExpression('1200'),
);
i1.GeneratedColumn<int> _column_67(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reminder_last_delivered_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deckId =>
      columnsByName['deck_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rootId =>
      columnsByName['root_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get generation =>
      columnsByName['generation']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sessionKind =>
      columnsByName['session_kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get currentMode =>
      columnsByName['current_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get endReason =>
      columnsByName['end_reason']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get cursor =>
      columnsByName['cursor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cardLimit =>
      columnsByName['card_limit']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get direction =>
      columnsByName['direction']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endedAt =>
      columnsByName['ended_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_68(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session_kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (session_kind IN (\'learning\', \'reviewing\'))',
    );
i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'current_mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (current_mode IN (\'browse\', \'self_assess\', \'match\', \'guess\', \'recall\', \'fill\'))',
    );
i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (status IN (\'in_progress\', \'completed\', \'abandoned\', \'invalidated\', \'failed\'))',
    );
i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'end_reason',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (end_reason IN (\'user_exit\', \'interrupted\', \'scheduler_reset\', \'scheduler_changed\', \'stale_generation\', \'persistence_error\', \'content_deleted\'))',
    );
i1.GeneratedColumn<int> _column_72(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cursor',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_73(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'direction',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (direction IS NULL OR direction IN (\'korean_to_meaning\', \'meaning_to_korean\', \'mixed\'))',
    );
i1.GeneratedColumn<int> _column_74(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_75(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ended_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mode =>
      columnsByName['mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get round =>
      columnsByName['round']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get cardId =>
      columnsByName['card_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get availableAt =>
      columnsByName['available_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get answersInSession =>
      columnsByName['answers_in_session']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get remainingMs =>
      columnsByName['remaining_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isRevealed =>
      columnsByName['is_revealed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get direction =>
      columnsByName['direction']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get hintShown =>
      columnsByName['hint_shown']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get meaningSlot =>
      columnsByName['meaning_slot']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_76(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES study_session(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_77(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'round',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (round >= 1)',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_78(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_79(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (status IN (\'pending\', \'completed\'))',
    );
i1.GeneratedColumn<int> _column_80(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'available_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (available_at >= 0)',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_81(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'answers_in_session',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (answers_in_session >= 0)',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_82(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'remaining_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'CHECK (remaining_ms IS NULL OR remaining_ms BETWEEN 0 AND 20000)',
    );
i1.GeneratedColumn<int> _column_83(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_revealed',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_revealed IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_84(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'hint_shown',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (hint_shown IN (0, 1) AND(mode = \'fill\' OR hint_shown = 0))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_85(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'meaning_slot',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'CHECK (meaning_slot IS NULL OR(mode = \'match\' AND meaning_slot BETWEEN 0 AND 4))',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mode =>
      columnsByName['mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get round =>
      columnsByName['round']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get cardId =>
      columnsByName['card_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get slot =>
      columnsByName['slot']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get optionCardId =>
      columnsByName['option_card_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_86(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'guess\' CHECK (mode = \'guess\')',
      defaultValue: const i1.CustomExpression('\'guess\''),
    );
i1.GeneratedColumn<int> _column_87(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'round',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_88(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'card_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_89(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'slot',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (slot BETWEEN 0 AND 4)',
    );
i1.GeneratedColumn<String> _column_90(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'option_card_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES card(id)ON DELETE CASCADE',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    deleteBatches,
    deck,
    card,
    cardSchedule,
    tags,
    cardTags,
    reviewLog,
    idxDeleteBatchesDeleted,
    appSettings,
    studySession,
    studyQueueItems,
    idxStudyQueuePending,
    studyGuessOptions,
    idxStudyGuessOptionsOption,
    idxCardScheduleDue,
    idxReviewLogCard,
    idxReviewLogSession,
    reviewLogAppendOnly,
    reviewLogNoDelete,
    idxTagsOwnerNameFolded,
    idxCardTagsTag,
    idxCardDeckCreated,
    idxCardDeleteBatch,
    idxDeckParentPosition,
    idxDeckRootPosition,
    idxDeckDeleteBatch,
  ];
  late final Shape10 deleteBatches = Shape10(
    source: i0.VersionedTable(
      entityName: 'delete_batches',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_91, _column_92, _column_93, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape0 deck = Shape0(
    source: i0.VersionedTable(
      entityName: 'deck',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((parent_id IS NULL)=(root_id = id))',
        'CHECK(parent_id IS NOT NULL OR content_type = \'deck\')',
        'CHECK((parent_id IS NULL)=(scheduler_type IS NOT NULL))',
        'CHECK((parent_id IS NULL)=(generation IS NOT NULL))',
        'CHECK((parent_id IS NULL)=(scheduler_version IS NOT NULL))',
        'CHECK(parent_id IS NULL OR scheduler_config IS NULL)',
        'CHECK(parent_id IS NULL OR study_config IS NULL)',
        'CHECK(parent_id IS NULL OR generation IS NULL)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_94,
        _column_16,
        _column_17,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 card = Shape1(
    source: i0.VersionedTable(
      entityName: 'card',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_94,
        _column_17,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 cardSchedule = Shape2(
    source: i0.VersionedTable(
      entityName: 'card_schedule',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((scheduler_type = \'eight_box\')=(current_box IS NOT NULL))',
        'CHECK((scheduler_type = \'sm2\')=(ease_factor IS NOT NULL))',
        'CHECK((ease_factor IS NULL)=(interval_days IS NULL))',
        'CHECK((ease_factor IS NULL)=(repetitions IS NULL))',
        'CHECK(learned_at IS NOT NULL OR due_at IS NULL)',
      ],
      columns: [
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 tags = Shape3(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_41, _column_6, _column_17],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 cardTags = Shape4(
    source: i0.VersionedTable(
      entityName: 'card_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(card_id, tag_id)'],
      columns: [_column_42, _column_43],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 reviewLog = Shape5(
    source: i0.VersionedTable(
      entityName: 'review_log',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(mode = \'fill\' OR(comparison_version IS NULL AND used_hint IS NULL))',
        'CHECK(outcome_reason IS NULL OR mode = \'recall\')',
      ],
      columns: [
        _column_0,
        _column_42,
        _column_44,
        _column_29,
        _column_31,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxDeleteBatchesDeleted = i1.Index(
    'idx_delete_batches_deleted',
    'CREATE INDEX idx_delete_batches_deleted ON delete_batches (deleted_at, id)',
  );
  late final Shape6 appSettings = Shape6(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 studySession = Shape7(
    source: i0.VersionedTable(
      entityName: 'study_session',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((status IN (\'in_progress\', \'completed\') AND end_reason IS NULL)OR(status = \'abandoned\' AND end_reason IN (\'user_exit\', \'interrupted\'))OR(status = \'invalidated\' AND end_reason IN (\'scheduler_reset\', \'scheduler_changed\', \'stale_generation\', \'content_deleted\'))OR(status = \'failed\' AND end_reason = \'persistence_error\'))',
        'CHECK((status = \'in_progress\')=(ended_at IS NULL))',
        'CHECK(direction IS NULL OR(session_kind = \'reviewing\' AND current_mode = \'self_assess\'))',
      ],
      columns: [
        _column_0,
        _column_19,
        _column_3,
        _column_31,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_61,
        _column_73,
        _column_74,
        _column_75,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 studyQueueItems = Shape8(
    source: i0.VersionedTable(
      entityName: 'study_queue_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(session_id, mode, round, card_id)',
        'CHECK(mode <> \'self_assess\' OR answers_in_session <= 4)',
        'CHECK(mode = \'recall\' OR(remaining_ms IS NULL AND is_revealed = 0))',
        'CHECK(mode = \'self_assess\' OR direction IS NULL)',
      ],
      columns: [
        _column_76,
        _column_46,
        _column_77,
        _column_42,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_83,
        _column_50,
        _column_84,
        _column_85,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxStudyQueuePending = i1.Index(
    'idx_study_queue_pending',
    'CREATE INDEX idx_study_queue_pending ON study_queue_items (session_id, status, available_at, position)',
  );
  late final Shape9 studyGuessOptions = Shape9(
    source: i0.VersionedTable(
      entityName: 'study_guess_options',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(session_id, mode, round, card_id, slot)',
        'UNIQUE(session_id, mode, round, card_id, option_card_id)',
        'FOREIGN KEY(session_id, mode, round, card_id)REFERENCES study_queue_items(session_id, mode, round, card_id)ON DELETE CASCADE',
      ],
      columns: [
        _column_44,
        _column_86,
        _column_87,
        _column_88,
        _column_89,
        _column_90,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxStudyGuessOptionsOption = i1.Index(
    'idx_study_guess_options_option',
    'CREATE INDEX idx_study_guess_options_option ON study_guess_options (option_card_id)',
  );
  final i1.Index idxCardScheduleDue = i1.Index(
    'idx_card_schedule_due',
    'CREATE INDEX idx_card_schedule_due ON card_schedule (due_at)',
  );
  final i1.Index idxReviewLogCard = i1.Index(
    'idx_review_log_card',
    'CREATE INDEX idx_review_log_card ON review_log (card_id, answered_at)',
  );
  final i1.Index idxReviewLogSession = i1.Index(
    'idx_review_log_session',
    'CREATE INDEX idx_review_log_session ON review_log (session_id)',
  );
  final i1.Trigger reviewLogAppendOnly = i1.Trigger(
    'CREATE TRIGGER review_log_append_only BEFORE UPDATE ON review_log BEGIN SELECT RAISE (ABORT, \'review_log is append-only\');END',
    'review_log_append_only',
  );
  final i1.Trigger reviewLogNoDelete = i1.Trigger(
    'CREATE TRIGGER review_log_no_delete BEFORE DELETE ON review_log WHEN OLD.card_id IN (SELECT id FROM card) BEGIN SELECT RAISE (ABORT, \'review_log rows are only removed by a card cascade\');END',
    'review_log_no_delete',
  );
  final i1.Index idxTagsOwnerNameFolded = i1.Index(
    'idx_tags_owner_name_folded',
    'CREATE UNIQUE INDEX idx_tags_owner_name_folded ON tags (COALESCE(owner_id, \'\'), name_folded)',
  );
  final i1.Index idxCardTagsTag = i1.Index(
    'idx_card_tags_tag',
    'CREATE INDEX idx_card_tags_tag ON card_tags (tag_id, card_id)',
  );
  final i1.Index idxCardDeckCreated = i1.Index(
    'idx_card_deck_created',
    'CREATE INDEX idx_card_deck_created ON card (deck_id, created_at, id)',
  );
  final i1.Index idxCardDeleteBatch = i1.Index(
    'idx_card_delete_batch',
    'CREATE INDEX idx_card_delete_batch ON card (delete_batch_id)',
  );
  final i1.Index idxDeckParentPosition = i1.Index(
    'idx_deck_parent_position',
    'CREATE INDEX idx_deck_parent_position ON deck (parent_id, sibling_position, id)',
  );
  final i1.Index idxDeckRootPosition = i1.Index(
    'idx_deck_root_position',
    'CREATE INDEX idx_deck_root_position ON deck (root_id, sibling_position, id)',
  );
  final i1.Index idxDeckDeleteBatch = i1.Index(
    'idx_deck_delete_batch',
    'CREATE INDEX idx_deck_delete_batch ON deck (delete_batch_id)',
  );
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get itemType =>
      columnsByName['item_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rootItemId =>
      columnsByName['root_item_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get ownerId =>
      columnsByName['owner_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_91(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'item_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (item_type IN (\'card\', \'deck\'))',
    );
i1.GeneratedColumn<String> _column_92(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'root_item_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_93(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_94(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'delete_batch_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'REFERENCES delete_batches(id)ON DELETE CASCADE',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
