spring:
  application:
    name: memox-api-services
  jackson:
    time-zone: UTC
  mvc:
    problemdetails:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-handlers-package: com.memox.common.type_handler
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
