#!/usr/bin/env python3
"""Generate the theme foundations from DESIGN.md (spec 2026-10-04-sp3a §3.2).

    python3 tools/design/generate.py --check    # the gate: validate, then fail if stale
    python3 tools/design/generate.py --write    # rewrite lib/core/theme/foundations/
    python3 tools/design/generate.py --report   # every contrast pair, both themes

Run from the repository root. DESIGN.md's frontmatter is the only place a colour
value is written by hand: every colour has a light key and a `-dark` key. The
sidecar (.impeccable/design.json `extensions`) holds only what the frontmatter
schema cannot: the semantic extension families, the contrast pairs, opacity,
stroke, motion, breakpoints and shadows. It holds no colour literal.

Exit code 1 when validation fails or, with --check, when the output is stale.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path


ROOT = Path.cwd()
DESIGN_MD = Path("DESIGN.md")
SIDECAR = Path(".impeccable/design.json")
OUT_DIR = Path("lib/core/theme/foundations")
HEADER = "// GENERATED by tools/design/generate.py from DESIGN.md — DO NOT EDIT.\n"

# The 45 non-deprecated colour roles of Flutter 3.47's ColorScheme, in its order.
_TONAL = ("", "on-{}", "{}-container", "on-{}-container", "{}-fixed", "{}-fixed-dim", "on-{}-fixed", "on-{}-fixed-variant")
M3_ROLES = [
    (f.format(p) if f else p) for p in ("primary", "secondary", "tertiary") for f in _TONAL
] + [
    "error", "on-error", "error-container", "on-error-container",
    "surface", "on-surface", "on-surface-variant", "surface-dim", "surface-bright",
    "surface-container-lowest", "surface-container-low", "surface-container",
    "surface-container-high", "surface-container-highest",
    "outline", "outline-variant", "shadow", "scrim",
    "inverse-surface", "on-inverse-surface", "inverse-primary",
]
TEXT_THEME_SLOTS = [
    f"{size}{scale}"
    for size in ("display", "headline", "title", "body", "label")
    for scale in ("Large", "Medium", "Small")
]
DARK = "-dark"
INK = re.compile(r"(?:^|-)ink(?:-|$)|[a-z0-9]Ink(?:[A-Z]|$)")
# Every way to write a colour value: hex, CSS colour functions, Dart's 0xAARRGGBB.
# `var(--color-…)` and `color-mix(` are references, not values, and stay allowed.
COLOUR_LITERAL = re.compile(
    r"#[0-9A-Fa-f]{3,8}\b|\b(?:rgba?|hsla?|hwb|lab|lch|oklab|oklch|color)\(|\b0x[0-9A-Fa-f]{6,8}\b",
    re.IGNORECASE,
)
HEX = re.compile(r"^#[0-9A-Fa-f]{6}$")
TOKEN_REF = re.compile(r"^\{(colors|typography|rounded|spacing)\.([a-z0-9-]+)\}$")


@dataclass
class Design:
    colors: dict[str, str]
    typography: dict[str, dict]
    rounded: dict[str, str]
    spacing: dict[str, str]
    components: dict[str, dict]
    text_theme: dict[str, str]
    sidecar_text: str
    extensions: dict


def camel(kebab: str) -> str:
    head, *rest = kebab.split("-")
    return head + "".join(part[:1].upper() + part[1:] for part in rest)


def px(value: object) -> float:
    return float(str(value).removesuffix("px"))


def number(value: float) -> str:
    """A Dart literal: `40`, `1.5`, `-0.64`."""
    return str(int(value)) if float(value).is_integer() else repr(float(value))


# ------------------------------------------------------------------ loading


def scalar(raw: str) -> object:
    raw = raw.strip()
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in "\"'":
        return raw[1:-1]
    try:
        return int(raw)
    except ValueError:
        pass
    try:
        return float(raw)
    except ValueError:
        return raw


def frontmatter(text: str) -> dict:
    """DESIGN.md's frontmatter: nested `key: value` maps indented by two spaces,
    scalars quoted or bare. That is all the design.md token schema uses, so no
    YAML library is needed."""
    if not text.startswith("---\n"):
        raise ValueError("DESIGN.md has no frontmatter")
    end = text.index("\n---\n", 4)
    root: dict = {}
    stack: list[tuple[int, dict]] = [(-1, root)]
    for number, line in enumerate(text[4:end].splitlines(), start=2):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        indent = len(line) - len(line.lstrip(" "))
        key, sep, value = line.strip().partition(":")
        if not sep:
            raise ValueError(f"DESIGN.md:{number}: expected `key: value`")
        while indent <= stack[-1][0]:
            stack.pop()
        parent = stack[-1][1]
        if key.strip() in parent:
            raise ValueError(f"DESIGN.md:{number}: `{key.strip()}` is defined twice")
        if value.strip():
            parent[key.strip()] = scalar(value)
            continue
        child: dict = {}
        parent[key.strip()] = child
        stack.append((indent, child))
    return root


def table_under(text: str, heading: str) -> list[list[str]]:
    """Body rows of the first Markdown table after `heading` (a whole line)."""
    lines = text.splitlines()
    try:
        start = lines.index(heading)
    except ValueError:
        return []
    rows: list[list[str]] = []
    for line in lines[start + 1:]:
        if line.startswith("#"):
            break
        if not line.startswith("|"):
            if rows:
                break
            continue
        cells = [cell.strip().strip("`") for cell in line.strip().strip("|").split("|")]
        if set("".join(cells)) <= set("-: "):
            continue
        rows.append(cells)
    return rows[1:]


def load(root: Path) -> Design:
    text = (root / DESIGN_MD).read_text(encoding="utf-8")
    front = frontmatter(text)
    sidecar_text = (root / SIDECAR).read_text(encoding="utf-8")
    sidecar = json.loads(sidecar_text)
    return Design(
        colors={str(k): str(v) for k, v in (front.get("colors") or {}).items()},
        typography=front.get("typography") or {},
        rounded=front.get("rounded") or {},
        spacing=front.get("spacing") or {},
        components=front.get("components") or {},
        text_theme={row[0]: row[1] for row in table_under(text, "### Text theme") if len(row) >= 2},
        sidecar_text=sidecar_text,
        extensions=sidecar.get("extensions") or {},
    )


# --------------------------------------------------------------- validation


def luminance(hex_colour: str) -> float:
    channels = [int(hex_colour[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    linear = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
    return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]


def contrast(a: str, b: str) -> float:
    high, low = sorted((luminance(a), luminance(b)), reverse=True)
    return (high + 0.05) / (low + 0.05)


def lab(hex_colour: str) -> tuple[float, float, float]:
    """CIE L*a*b* (D65) of an sRGB colour."""
    channels = [int(hex_colour[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    r, g, b = [c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
    x = (r * 0.4124 + g * 0.3576 + b * 0.1805) / 0.95047
    y = r * 0.2126 + g * 0.7152 + b * 0.0722
    z = (r * 0.0193 + g * 0.1192 + b * 0.9505) / 1.08883

    def f(t: float) -> float:
        return t ** (1 / 3) if t > 0.008856 else 7.787 * t + 16 / 116

    fx, fy, fz = f(x), f(y), f(z)
    return 116 * fy - 16, 500 * (fx - fy), 200 * (fy - fz)


def delta_e(a: str, b: str) -> float:
    """CIE76 colour difference: about 2.3 is just noticeable, 15 reads as another colour."""
    return sum((p - q) ** 2 for p, q in zip(lab(a), lab(b))) ** 0.5


def base_keys(design: Design) -> list[str]:
    return [key for key in design.colors if not key.endswith(DARK)]


def validate(design: Design) -> list[str]:
    errors: list[str] = []
    colors = design.colors
    for key, value in colors.items():
        if not HEX.match(value):
            errors.append(f"colour `{key}` is `{value}`, not #RRGGBB")
        if INK.search(key.removesuffix(DARK)):
            errors.append(f"colour `{key}` is an ink role; the ink model is retired (A2, A11)")
    for key in base_keys(design):
        if key + DARK not in colors:
            errors.append(f"colour `{key}` has no `{key}{DARK}` value")
    for key in colors:
        if not key.endswith(DARK):
            continue
        light = key.removesuffix(DARK)
        if light.endswith(DARK):
            errors.append(f"colour `{key}` repeats `{DARK}`")
        elif light not in colors:
            errors.append(f"colour `{key}` has no light value `{light}`")
    for role in M3_ROLES:
        if role not in colors:
            errors.append(f"Material 3 role `{role}` is missing")

    families: dict[str, list[str]] = design.extensions.get("semanticExtensions") or {}
    members = {member for family in families.values() for member in family}
    for family, family_members in families.items():
        for member in family_members:
            if INK.search(member):
                errors.append(f"extension `{family}` member `{member}` is an ink role (A11)")
            if member not in colors:
                errors.append(f"extension `{family}` member `{member}` has no colour in DESIGN.md")
    for key in base_keys(design):
        if key not in M3_ROLES and key not in members:
            errors.append(f"colour `{key}` is neither a Material 3 role nor a declared extension member")

    if COLOUR_LITERAL.search(design.sidecar_text):
        errors.append(f"{SIDECAR} holds a colour literal; colour values live only in DESIGN.md (A3)")

    for pair in design.extensions.get("contrastPairs") or []:
        fg, bg, minimum = pair["fg"], pair["bg"], float(pair["min"])
        for theme, suffix in (("light", ""), ("dark", DARK)):
            a, b = colors.get(fg + suffix), colors.get(bg + suffix)
            if a is None or b is None or not HEX.match(a) or not HEX.match(b):
                errors.append(f"contrast pair `{fg}` on `{bg}` names an unknown colour")
                break
            ratio = contrast(a, b)
            if ratio < minimum:
                errors.append(f"contrast: `{fg}` on `{bg}` is {ratio:.2f}:1 in {theme}, below {minimum}:1")

    for pair in design.extensions.get("distinctPairs") or []:
        a, b, minimum = pair["a"], pair["b"], float(pair["minDeltaE"])
        for theme, suffix in (("light", ""), ("dark", DARK)):
            x, y = colors.get(a + suffix), colors.get(b + suffix)
            if x is None or y is None or not HEX.match(x) or not HEX.match(y):
                errors.append(f"distinct pair `{a}` / `{b}` names an unknown colour")
                break
            difference = delta_e(x, y)
            if difference < minimum:
                errors.append(f"`{a}` and `{b}` differ by ΔE {difference:.1f} in {theme}, below ΔE {minimum:g}; they must read as two colours")

    for slot in TEXT_THEME_SLOTS:
        role = design.text_theme.get(slot)
        if role is None:
            errors.append(f"TextTheme slot `{slot}` has no role in DESIGN.md `### Text theme`")
        elif role not in design.typography:
            errors.append(f"TextTheme slot `{slot}` names unknown typography role `{role}`")
    for slot in design.text_theme:
        if slot not in TEXT_THEME_SLOTS:
            errors.append(f"`### Text theme` names `{slot}`, which is not a TextTheme slot")

    groups = {"colors": colors, "typography": design.typography, "rounded": design.rounded, "spacing": design.spacing}
    for name, props in design.components.items():
        for prop, value in (props or {}).items():
            match = TOKEN_REF.match(str(value))
            if match and match.group(2) not in groups[match.group(1)]:
                errors.append(f"component `{name}` `{prop}` refers to unknown `{value}`")
    return errors


def report(design: Design) -> list[str]:
    lines = []
    for pair in design.extensions.get("contrastPairs") or []:
        fg, bg = pair["fg"], pair["bg"]
        light = contrast(design.colors[fg], design.colors[bg])
        dark = contrast(design.colors[fg + DARK], design.colors[bg + DARK])
        lines.append(f"{fg:32} on {bg:28} light {light:5.2f}  dark {dark:5.2f}  min {pair['min']}")
    return lines


# ----------------------------------------------------------------- emission


def colour(value: str) -> str:
    return f"Color(0xFF{value[1:].upper()})"


def emit_color_schemes(design: Design) -> str:
    def scheme(name: str, brightness: str, suffix: str) -> str:
        args = "".join(f"    {camel(role)}: {colour(design.colors[role + suffix])},\n" for role in M3_ROLES)
        return f"  static const ColorScheme {name} = ColorScheme(\n    brightness: Brightness.{brightness},\n{args}  );\n"

    return (
        HEADER + "import 'package:flutter/material.dart';\n\n"
        "/// The 45 Material 3 roles of each theme, from DESIGN.md.\n"
        "abstract final class AppColorSchemes {\n"
        + scheme("light", "light", "") + "\n" + scheme("dark", "dark", DARK) + "}\n"
    )


def emit_semantic_colors(design: Design) -> str:
    families: dict[str, list[str]] = design.extensions["semanticExtensions"]
    fields = [camel(member) for family in families.values() for member in family]
    kebab = [member for family in families.values() for member in family]

    def instance(name: str, suffix: str) -> str:
        args = "".join(f"    {camel(k)}: {colour(design.colors[k + suffix])},\n" for k in kebab)
        return f"  static const AppSemanticColors {name} = AppSemanticColors(\n{args}  );\n"

    ctor = "".join(f"    required this.{f},\n" for f in fields)
    decl = "".join(f"  final Color {f};\n" for f in fields)
    copy_params = "".join(f"    Color? {f},\n" for f in fields)
    copy_args = "".join(f"      {f}: {f} ?? this.{f},\n" for f in fields)
    lerp_args = "".join(f"      {f}: Color.lerp({f}, other.{f}, t)!,\n" for f in fields)
    return (
        HEADER + "import 'package:flutter/material.dart';\n\n"
        "/// MemoX semantic colours beside the Material 3 scheme (spec 2026-10-04-sp3a A2).\n"
        "@immutable\n"
        "final class AppSemanticColors extends ThemeExtension<AppSemanticColors> {\n"
        f"  const AppSemanticColors({{\n{ctor}  }});\n\n"
        + instance("light", "") + "\n" + instance("dark", DARK) + "\n" + decl + "\n"
        "  @override\n"
        f"  AppSemanticColors copyWith({{\n{copy_params}  }}) {{\n    return AppSemanticColors(\n{copy_args}    );\n  }}\n\n"
        "  @override\n"
        "  AppSemanticColors lerp(AppSemanticColors? other, double t) {\n"
        "    if (other == null) {\n      return this;\n    }\n"
        f"    return AppSemanticColors(\n{lerp_args}    );\n  }}\n"
        "}\n"
    )


def emit_text_styles(design: Design) -> str:
    families = {str(spec["fontFamily"]) for spec in design.typography.values()}
    if len(families) != 1:
        raise ValueError(f"DESIGN.md typography uses {sorted(families)}; one family is expected")
    body = [f"  static const String family = '{families.pop()}';\n"]
    for role, spec in design.typography.items():
        args = ["fontFamily: family", f"fontSize: {number(px(spec['fontSize']))}"]
        if "lineHeight" in spec:
            args.append(f"height: {number(float(spec['lineHeight']))}")
        if "letterSpacing" in spec:
            args.append(f"letterSpacing: {number(px(spec['letterSpacing']))}")
        if spec.get("fontFeature") == "tnum":
            args.append("fontFeatures: <FontFeature>[FontFeature.tabularFigures()]")
        body.append(
            f"\n  static final TextStyle {camel(role)} = AppTypography.withWeight(\n"
            f"    const TextStyle({', '.join(args)}),\n"
            f"    FontWeight.w{int(spec['fontWeight'])},\n  );\n"
        )
    slots = "".join(f"    {slot}: {camel(design.text_theme[slot])},\n" for slot in TEXT_THEME_SLOTS)
    body.append(f"\n  static final TextTheme textTheme = TextTheme(\n{slots}  );\n")
    return (
        HEADER + "import 'package:flutter/material.dart';\n"
        "import 'package:memox/core/theme/app_typography.dart';\n\n"
        "/// DESIGN.md's typography roles and its TextTheme mapping.\n"
        "abstract final class AppTextStyles {\n" + "".join(body) + "}\n"
    )


def emit_scale(class_name: str, doc: str, values: dict[str, object], kind: str = "double") -> str:
    lines = []
    for name, value in values.items():
        if kind == "Duration":
            lines.append(f"  static const Duration {camel(name)} = Duration(milliseconds: {int(value)});\n")
        else:
            lines.append(f"  static const double {camel(name)} = {number(px(value))};\n")
    return HEADER + f"\n/// {doc}\nabstract final class {class_name} {{\n" + "".join(lines) + "}\n"


def emit_shadows(design: Design) -> str:
    shadows: dict[str, dict] = design.extensions["shadows"]
    lines = []
    for name, themes in shadows.items():
        for theme in ("light", "dark"):
            spec = themes.get(theme)
            field = f"{camel(name)}{theme.capitalize()}"
            if spec is None:
                lines.append(f"  static const AppShadow? {field} = null;\n")
                continue
            lines.append(
                f"  static const AppShadow {field} = AppShadow(dy: {number(spec['dy'])}, "
                f"blur: {number(spec['blur'])}, alpha: {number(spec['alpha'])});\n"
            )
    return (
        HEADER + "import 'package:flutter/material.dart';\n\n"
        "/// One named shadow: an offset, a blur and an alpha over the scheme's `shadow` role.\n"
        "@immutable\nfinal class AppShadow {\n"
        "  const AppShadow({required this.dy, required this.blur, required this.alpha});\n\n"
        "  final double dy;\n  final double blur;\n  final double alpha;\n\n"
        "  BoxShadow on(Color shadow) => BoxShadow(\n"
        "    color: shadow.withValues(alpha: alpha),\n    offset: Offset(0, dy),\n    blurRadius: blur,\n  );\n}\n\n"
        "/// DESIGN.md's shadow vocabulary; `null` where a theme draws none.\n"
        "abstract final class AppShadows {\n" + "".join(lines) + "}\n"
    )


def emit(design: Design) -> dict[Path, str]:
    ext = design.extensions
    return {
        OUT_DIR / "app_color_schemes.dart": emit_color_schemes(design),
        OUT_DIR / "app_semantic_colors.dart": emit_semantic_colors(design),
        OUT_DIR / "app_text_styles.dart": emit_text_styles(design),
        OUT_DIR / "app_spacing.dart": emit_scale("AppSpacing", "The spacing steps.", design.spacing),
        OUT_DIR / "app_radius.dart": emit_scale("AppRadius", "Corner radii.", design.rounded),
        OUT_DIR / "app_stroke.dart": emit_scale("AppStroke", "Stroke widths.", ext["stroke"]),
        OUT_DIR / "app_opacity.dart": emit_scale("AppOpacity", "Named opacities.", ext["opacity"]),
        OUT_DIR / "app_breakpoints.dart": emit_scale("AppBreakpoints", "Window-width breakpoints.", ext["breakpoints"]),
        OUT_DIR / "app_durations.dart": emit_scale("AppDurations", "Motion and dwell durations.", ext["motion"], "Duration"),
        OUT_DIR / "app_shadows.dart": emit_shadows(design),
    }


# ------------------------------------------------------------------ running

Formatter = Callable[[Path, str], str]


def dart_format(path: Path, source: str) -> str:
    dart = shutil.which("dart")
    if dart is None:
        raise RuntimeError("dart is not on PATH; the generator formats its output with `dart format`")
    result = subprocess.run(
        [dart, "format", f"--stdin-name={path.as_posix()}"],
        input=source, capture_output=True, text=True, encoding="utf-8", check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"dart format failed on {path}:\n{result.stderr}")
    return result.stdout


def stale(root: Path, design: Design, fmt: Formatter = dart_format) -> list[str]:
    expected = {path: fmt(path, source) for path, source in emit(design).items()}
    problems = []
    for path, source in expected.items():
        target = root / path
        if not target.exists():
            problems.append(f"{path} is missing; run tools/design/generate.py --write")
        elif target.read_text(encoding="utf-8") != source:
            problems.append(f"{path} is stale or edited by hand; run tools/design/generate.py --write")
    folder = root / OUT_DIR
    if folder.is_dir():
        for path in sorted(folder.glob("*.dart")):
            if path.relative_to(root) not in expected:
                problems.append(f"{path.relative_to(root)} is in the generated folder but not generated")
    return problems


def write(root: Path, design: Design, fmt: Formatter = dart_format) -> None:
    (root / OUT_DIR).mkdir(parents=True, exist_ok=True)
    for path, source in emit(design).items():
        (root / path).write_text(fmt(path, source), encoding="utf-8", newline="\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--report", action="store_true")
    args = parser.parse_args(argv)
    design = load(ROOT)
    errors = validate(design)
    for error in errors:
        print(f"ERROR {error}")
    if errors:
        return 1
    if args.report:
        print("\n".join(report(design)))
        return 0
    if args.write:
        write(ROOT, design)
        print(f"wrote {len(emit(design))} files to {OUT_DIR}")
        return 0
    problems = stale(ROOT, design)
    for problem in problems:
        print(f"ERROR {problem}")
    if problems:
        return 1
    print("PASS — design tokens are valid and the generated theme is fresh")
    return 0


if __name__ == "__main__":
    sys.exit(main())
