"""Compiles the DESIGN.md frontmatter into the app's design values.

    python3 tools/design/generate.py          # write the three outputs
    python3 tools/design/generate.py --check  # fail if any output is stale

Outputs (spec 2026-10-04-sp3a §5.1):
- lib/core/theme/generated/design_values.dart
- the value sections of .impeccable/design.json
- the reference block in DESIGN.md, between the generated markers

The frontmatter is the only source; nothing here is edited by hand.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from designdata import (  # noqa: E402
    M3_ROLES, SEMANTIC_COLORS, SHADOWS, THEMES, TYPE_SLOTS,
    DesignData, camel, load, prose_drift, read_frontmatter,
)

ROOT = Path(__file__).resolve().parents[2]
DESIGN_MD = "DESIGN.md"
DESIGN_JSON = ".impeccable/design.json"
DART_OUT = "lib/core/theme/generated/design_values.dart"
BLOCK_START = "<!-- generated:design-values:start -->"
BLOCK_END = "<!-- generated:design-values:end -->"
COMMAND = "python3 tools/design/generate.py"

TOKEN_CLASSES = (
    ("spacing", "AppSpacing", "double"),
    ("rounded", "AppRadius", "double"),
    ("opacity", "AppOpacity", "double"),
    ("stroke", "AppStroke", "double"),
    ("size", "AppSize", "double"),
    ("icon-size", "AppIconSize", "double"),
    ("breakpoints", "AppBreakpoints", "double"),
    ("effects", "AppEffects", "double"),
)


def _num(value: float) -> str:
    return f"{value:g}" if value != int(value) else f"{int(value)}"


def dart(data: DesignData) -> str:
    out = [
        f"// GENERATED by `{COMMAND}` from the DESIGN.md frontmatter.",
        "// Do not edit: change DESIGN.md, then run the generator.",
        "// Spec 2026-10-04-sp3a §5.1. The only file in lib/ that holds a colour literal.",
        "library;",
        "",
        "import 'package:flutter/painting.dart';",
        "",
    ]
    out += _palette(data)
    out += _tokens(data)
    out += _type(data)
    out += _contrast(data)
    return "\n".join(out) + "\n"


def _colour_names(data: DesignData) -> list[str]:
    return list(M3_ROLES + SEMANTIC_COLORS) + list(data.rules)


def _palette(data: DesignData) -> list[str]:
    names = _colour_names(data)
    shadows = [f"shadow{name[:1].upper()}{name[1:]}" for name in SHADOWS]
    out = [
        "/// One theme's colours (DESIGN.md `colors`, `colors-dark`, `derived`) and",
        "/// shadows (`shadows`, `shadows-dark`).",
        "final class DesignPalette {",
        "  const DesignPalette({",
        *[f"    required this.{camel(n)}," for n in names],
        *[f"    required this.{s}," for s in shadows],
        "  });",
        "",
        *[f"  final Color {camel(n)};" for n in names],
        *[f"  final List<BoxShadow> {s};" for s in shadows],
        "",
        "  /// Every colour by its DESIGN.md name, for the contrast and parity tests.",
        "  Map<String, Color> get byName => {",
        *[f"    '{n}': {camel(n)}," for n in names],
        "  };",
        "",
    ]
    for theme in THEMES:
        palette = data.colors[theme]
        out.append(f"  static const DesignPalette {theme} = DesignPalette(")
        for n in names:
            out.append(f"    {camel(n)}: Color({palette[n].argb()}),")
        shadow_base = palette["shadow"].hex[1:]
        for name, field in zip(SHADOWS, shadows):
            s = data.shadows[theme][name]
            if s.alpha == 0:
                out.append(f"    {field}: <BoxShadow>[],")
                continue
            alpha = f"{int(s.alpha * 255 + 0.5):02X}"
            out.append(
                f"    {field}: <BoxShadow>[BoxShadow(color: Color(0x{alpha}{shadow_base}), "
                f"offset: Offset({_num(s.x)}, {_num(s.y)}), blurRadius: {_num(s.blur)})],"
            )
        out += ["  );", ""]
    out[-1:] = ["}", ""]
    return out


def _tokens(data: DesignData) -> list[str]:
    out: list[str] = []
    for section, name, kind in TOKEN_CLASSES:
        out.append(f"/// DESIGN.md `{section}`.")
        out.append(f"abstract final class {name} {{")
        for key, value in data.numbers[section].items():
            out.append(f"  static const {kind} {camel(key)} = {_num(value)};")
        out += ["}", ""]
    out.append("/// DESIGN.md `motion`, in milliseconds.")
    out.append("abstract final class AppDurations {")
    for key, value in data.numbers["motion"].items():
        out.append(f"  static const Duration {camel(key)} = Duration(milliseconds: {int(value)});")
    out += ["}", ""]
    return out


def _type(data: DesignData) -> list[str]:
    family = next(iter(data.type_roles.values())).family
    out = [
        "/// The metrics of one DESIGN.md typography role.",
        "final class DesignTypeSpec {",
        "  const DesignTypeSpec({",
        "    required this.size,",
        "    required this.weight,",
        "    required this.height,",
        "    required this.letterSpacing,",
        "    required this.hasTabularFigures,",
        "  });",
        "",
        "  final double size;",
        "  final FontWeight weight;",
        "  final double height;",
        "  final double letterSpacing;",
        "  final bool hasTabularFigures;",
        "}",
        "",
        "/// DESIGN.md `typography`, one constant per role.",
        "abstract final class DesignType {",
        f"  static const String fontFamily = '{family}';",
    ]
    for key, role in data.type_roles.items():
        out.append(
            f"  static const DesignTypeSpec {camel(key)} = DesignTypeSpec(size: {_num(role.size)}, "
            f"weight: FontWeight({role.weight}), height: {_num(role.height)}, "
            f"letterSpacing: {_num(role.letter_spacing)}, hasTabularFigures: {'true' if role.tabular else 'false'});"
        )
    out += ["}", "", "/// DESIGN.md `type-slots`: the role behind each Material 3 TextTheme slot.",
            "abstract final class DesignTypeSlots {"]
    for slot in TYPE_SLOTS:
        out.append(f"  static const DesignTypeSpec {camel(slot)} = DesignType.{camel(data.type_slots[slot])};")
    out += ["}", ""]
    return out


def _contrast(data: DesignData) -> list[str]:
    out = [
        "/// One DESIGN.md `contrast` pair: [foreground] on [ground] holds [floor]:1.",
        "final class DesignContrastPair {",
        "  const DesignContrastPair(this.foreground, this.ground, this.floor);",
        "",
        "  final String foreground;",
        "  final String ground;",
        "  final double floor;",
        "}",
        "",
        "const List<DesignContrastPair> designContrastPairs = [",
    ]
    for fg, ground, floor in data.contrast:
        out.append(f"  DesignContrastPair('{fg}', '{ground}', {floor:g}),")
    out += ["];"]
    return out


def design_json(data: DesignData, current: str) -> str:
    doc = json.loads(current)
    ext = doc.setdefault("extensions", {})
    meta = ext.setdefault("colorMeta", {})
    for name in M3_ROLES + SEMANTIC_COLORS:
        entry = meta.setdefault(name, {"role": name, "displayName": name.replace("-", " ").title()})
        entry["canonical"] = data.colors["light"][name].hex
        entry["light"] = data.colors["light"][name].hex
        entry["dark"] = data.colors["dark"][name].hex
    purposes = {item["name"]: item.get("purpose", "") for item in ext.get("shadows", [])}
    ext["shadows"] = [
        {"name": name, "value": f"light: {_css(data, 'light', name)}; dark: {_css(data, 'dark', name)}",
         "purpose": purposes.get(name, "")}
        for name in SHADOWS
    ]
    motion = {item["name"]: item.get("purpose", "") for item in ext.get("motion", [])}
    ext["motion"] = [
        {"name": key, "value": f"{int(ms)}ms", "purpose": motion.get(key, "")}
        for key, ms in data.numbers["motion"].items()
    ]
    ext["breakpoints"] = [
        {"name": key, "value": f"{_num(dp)}dp"} for key, dp in data.numbers["breakpoints"].items()
    ]
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def _css(data: DesignData, theme: str, name: str) -> str:
    s = data.shadows[theme][name]
    if s.alpha == 0:
        return "none"
    r, g, b = (int(data.colors[theme]["shadow"].hex[i:i + 2], 16) for i in (1, 3, 5))
    x = f"{_num(s.x)}px" if s.x else "0"
    return f"{x} {_num(s.y)}px {_num(s.blur)}px rgba({r},{g},{b},{s.alpha:g})"


def reference_block(data: DesignData) -> list[str]:
    measured: dict[tuple[str, str], float] = {}
    for theme, fg, ground, _, ratio in data.measured:
        key = (fg, theme)
        measured[key] = min(measured.get(key, ratio), ratio)
    out = [
        BLOCK_START,
        f"<!-- Written by `{COMMAND}` from the frontmatter. Do not edit. -->",
        "",
        "| Colour | Light | Dark | Rule | Lowest contrast (light / dark) |",
        "|---|---|---|---|---|",
    ]
    for name in _colour_names(data):
        light, dark = data.colors["light"][name], data.colors["dark"][name]
        rule = data.rules.get(name)
        how = "stated" if rule is None else f"{rule['light'].describe()} / {rule['dark'].describe()}"
        ratios = " / ".join(
            f"{measured[(name, t)]:.2f}" if (name, t) in measured else "—" for t in THEMES
        )
        out.append(f"| `{name}` | {_swatch(light)} | {_swatch(dark)} | {how} | {ratios} |")
    out += ["", BLOCK_END]
    return out


def _swatch(colour) -> str:
    return colour.hex if colour.alpha == 1.0 else f"{colour.hex} @ {colour.alpha:.0%}"


def with_block(text: str, block: list[str]) -> str | None:
    lines = text.split("\n")
    try:
        start, end = lines.index(BLOCK_START), lines.index(BLOCK_END)
    except ValueError:
        return None
    return "\n".join(lines[:start] + block + lines[end + 1:])


def dart_format(text: str, root: Path) -> str:
    """The text as `dart format` writes it, so the gate's format step agrees."""
    dart_bin = shutil.which("dart")
    if dart_bin is None:
        raise RuntimeError("`dart` is not on PATH; the generator formats its Dart output with it")
    result = subprocess.run(
        [dart_bin, "format", "--output=show", f"--stdin-name={DART_OUT}"],
        input=text, capture_output=True, text=True, cwd=root, check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"dart format failed: {result.stderr.strip()}")
    return result.stdout


def build(
    root: Path, formatter: Callable[[str, Path], str] = dart_format
) -> tuple[dict[str, str], list[str]]:
    """Every output, keyed by its repo-relative path, or the errors."""
    design_text = (root / DESIGN_MD).read_text(encoding="utf-8")
    data, errors = load(design_text)
    if data is None:
        return {}, errors
    _, body, first = read_frontmatter(design_text)
    errors += prose_drift(body, first, data, (BLOCK_START, BLOCK_END))
    design_md = with_block(design_text, reference_block(data))
    if design_md is None:
        errors.append(f"DESIGN.md: the `{BLOCK_START}` and `{BLOCK_END}` markers are missing")
    if errors:
        return {}, errors
    return {
        DART_OUT: formatter(dart(data), root),
        DESIGN_JSON: design_json(data, (root / DESIGN_JSON).read_text(encoding="utf-8")),
        DESIGN_MD: design_md,
    }, []


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if an output is stale")
    parser.add_argument("--root", type=Path, default=ROOT, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    try:
        outputs, errors = build(args.root)
    except RuntimeError as error:
        print(f"ERROR {error}")
        return 1
    if errors:
        for error in errors:
            print(f"ERROR {error}")
        print(f"FAIL — {len(errors)} error(s) in the design source")
        return 1
    stale = [
        path for path, text in outputs.items()
        if not (args.root / path).is_file() or (args.root / path).read_text(encoding="utf-8") != text
    ]
    if args.check:
        for path in stale:
            print(f"ERROR {path}: stale — run `{COMMAND}`")
        print(f"{'FAIL' if stale else 'PASS'} — {len(stale)} stale output(s)")
        return 1 if stale else 0
    for path in stale:
        target = args.root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(outputs[path], encoding="utf-8")
        print(f"wrote {path}")
    print(f"PASS — {len(stale)} output(s) written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
