#!/usr/bin/env python3
"""Split the MemoX V3 Flutter handoff JSON into Markdown, deterministically.

    python tools/split_handoff.py <handoff.json> <output-dir>

Every "spec" string is written byte-for-byte: no trimming, no added newline,
no header. Everything else (index, traceability) is derived from the JSON with
no timestamps, so the same JSON always produces the same bytes. Re-running is
safe: unchanged files are left untouched, and files that an earlier run wrote
but the new JSON no longer produces are removed (tracked in a manifest, so
nothing the script did not create is ever deleted).

Outputs:
    00-index.md            widget / section / action / runnableAfter / composition / file
    01-foundations.md      $.foundations.spec
    02-theme-binding.md    $.themeHandoff.spec
    widgets/<kebab>.md     $.widgets[i].spec, named from $.widgets[i].name
    99-traceability.md     every output -> its source JSON path
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

INDEX_FILE = "00-index.md"
FOUNDATIONS_FILE = "01-foundations.md"
THEME_FILE = "02-theme-binding.md"
TRACE_FILE = "99-traceability.md"
WIDGETS_DIR = "widgets"
MANIFEST_FILE = ".handoff-split-manifest.json"
EMPTY = "—"


class SplitError(Exception):
    """The JSON does not have the shape this script relies on."""


@dataclass(frozen=True)
class Output:
    path: str  # relative to the output dir, always "/"-separated
    content: str
    source: str  # JSON path(s) this file comes from
    kind: str  # "verbatim" | "derived"
    note: str = ""


def kebab(name: str) -> str:
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", name)
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", s)
    s = re.sub(r"[^A-Za-z0-9]+", "-", s).strip("-").lower()
    if not s:
        raise SplitError(f"cannot derive a file name from widget name {name!r}")
    return s


def _dig(node, *keys, default=None):
    for key in keys:
        if not isinstance(node, dict) or key not in node:
            return default
        node = node[key]
    return node


def _spec(node, json_path: str) -> str:
    if not isinstance(node, str) or not node:
        raise SplitError(f"{json_path} must be a non-empty string")
    return node


def _cell(value) -> str:
    if value is None or value == "":
        return EMPTY
    return str(value).replace("|", "\\|").replace("\r", " ").replace("\n", " ")


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _widget_outputs(data: dict) -> list[tuple[Output, dict]]:
    widgets = data.get("widgets")
    if not isinstance(widgets, list):
        raise SplitError("$.widgets must be a list")
    seen: dict[str, str] = {}
    result = []
    for i, w in enumerate(widgets):
        where = f"$.widgets[{i}]"
        if not isinstance(w, dict) or not isinstance(w.get("name"), str):
            raise SplitError(f"{where}.name must be a string")
        name = w["name"]
        path = f"{WIDGETS_DIR}/{kebab(name)}.md"
        if path in seen:
            raise SplitError(f"{where} ({name!r}) and {seen[path]} both map to {path}")
        seen[path] = f"{where} ({name!r})"
        output = Output(
            path, _spec(w.get("spec"), f"{where}.spec"), f"{where}.spec", "verbatim", name
        )
        result.append((output, w))
    return result


def _build_index(data: dict, input_name: str, docs: list[Output],
                 widgets: list[tuple[Output, dict]]) -> str:
    composition = _dig(data, "themeHandoff", "views", "componentComposition", default={})
    order = _dig(data, "implementationOrder", default=[])
    lines = [
        "# MemoX V3 handoff — index",
        "",
        f"> Generated by `tools/split_handoff.py` from `{input_name}`. "
        "Do not edit by hand; regenerate from the JSON.",
        "",
        f"- JSON `generated`: {_cell(data.get('generated'))}",
        f"- JSON `source`: {_cell(data.get('source'))}",
        f"- JSON `contract`: {_cell(data.get('contract'))}",
        "- Run order (`implementationOrder`): "
        + (" → ".join(map(str, order)) if order else EMPTY),
        "",
        "## Usage (verbatim from JSON `usage`)",
        "",
        f"> {_cell(data.get('usage'))}",
        "",
        "## Documents",
        "",
        "| Document | Step | Mode / kind | Runnable after | File |",
        "|---|---|---|---|---|",
    ]
    for output, name, step, mode in (
        (docs[0], "Foundations", _dig(data, "foundations", "step"),
         _dig(data, "foundations", "handoffMode")),
        (docs[1], "Theme binding", _dig(data, "themeHandoff", "step"),
         _dig(data, "themeHandoff", "kind")),
    ):
        lines.append(
            f"| {name} | {_cell(step)} | {_cell(mode)} | {EMPTY} "
            f"| [{output.path}]({output.path}) |"
        )
    lines += [
        "",
        f"## Widgets ({len(widgets)})",
        "",
        "Composition comes from `$.themeHandoff.views.componentComposition`; "
        f"`{EMPTY}` means the JSON lists none.",
        "",
        "| Widget | Section | Action | Runnable after | Composition | File |",
        "|---|---|---|---|---|---|",
    ]
    for output, w in widgets:
        parts = composition.get(w["name"]) if isinstance(composition, dict) else None
        composes = "<br>".join(_cell(p) for p in parts) if parts else EMPTY
        lines.append(
            f"| {_cell(w['name'])} | {_cell(w.get('section'))} "
            f"| {_cell(w.get('implementationAction'))} | {_cell(w.get('runnableAfter'))} "
            f"| {composes} | [{output.path}]({output.path}) |"
        )
    return "\n".join(lines) + "\n"


def _build_trace(input_name: str, input_sha: str, outputs: list[Output]) -> str:
    lines = [
        "# MemoX V3 handoff — traceability",
        "",
        f"> Generated by `tools/split_handoff.py`. Input `{input_name}` "
        f"(SHA-256 `{input_sha}`).",
        "> `verbatim` files are exactly the JSON string, so their SHA-256 and length "
        "match it; `derived` files are built from the listed paths.",
        "",
        "| Output | Kind | Source JSON path | Widget | SHA-256 | Chars |",
        "|---|---|---|---|---|---|",
    ]
    for o in outputs:
        lines.append(
            f"| [{o.path}]({o.path}) | {o.kind} | `{o.source}` | {_cell(o.note)} "
            f"| `{_sha(o.content)}` | {len(o.content)} |"
        )
    lines.append(
        f"| {TRACE_FILE} | derived | all of the above | {EMPTY} | {EMPTY} | {EMPTY} |"
    )
    return "\n".join(lines) + "\n"


def build_outputs(data, input_name: str, input_sha: str) -> list[Output]:
    if not isinstance(data, dict):
        raise SplitError("top-level JSON value must be an object")
    docs = [
        Output(FOUNDATIONS_FILE,
               _spec(_dig(data, "foundations", "spec"), "$.foundations.spec"),
               "$.foundations.spec", "verbatim"),
        Output(THEME_FILE,
               _spec(_dig(data, "themeHandoff", "spec"), "$.themeHandoff.spec"),
               "$.themeHandoff.spec", "verbatim"),
    ]
    widgets = _widget_outputs(data)
    index = Output(
        INDEX_FILE,
        _build_index(data, input_name, docs, widgets),
        "$.generated, $.source, $.contract, $.usage, $.implementationOrder, "
        "$.foundations.{step,handoffMode}, $.themeHandoff.{step,kind}, "
        "$.widgets[*].{name,section,implementationAction,runnableAfter}, "
        "$.themeHandoff.views.componentComposition",
        "derived",
    )
    outputs = [index, *docs, *(o for o, _ in widgets)]
    trace = Output(
        TRACE_FILE,
        _build_trace(input_name, input_sha, outputs),
        "all outputs above",
        "derived",
    )
    return [*outputs, trace]


def write_outputs(out_dir: Path, outputs: list[Output]) -> tuple[int, int, int]:
    """Write changed files, remove files an earlier run wrote and this one did not."""
    out_dir.mkdir(parents=True, exist_ok=True)
    manifest = out_dir / MANIFEST_FILE
    try:
        previous = set(json.loads(manifest.read_text(encoding="utf-8")))
    except (OSError, ValueError):
        previous = set()

    written = unchanged = 0
    for o in outputs:
        target = out_dir / o.path
        data = o.content.encode("utf-8")  # bytes: no newline translation on Windows
        if target.is_file() and target.read_bytes() == data:
            unchanged += 1
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        written += 1

    current = {o.path for o in outputs}
    removed = 0
    root = out_dir.resolve()
    for rel in sorted(previous - current):
        target = (out_dir / rel).resolve()
        if root in target.parents and target.is_file():
            target.unlink()
            removed += 1
            try:
                target.parent.rmdir()  # only succeeds when empty
            except OSError:
                pass

    manifest_bytes = (json.dumps(sorted(current), indent=2) + "\n").encode("utf-8")
    if not manifest.is_file() or manifest.read_bytes() != manifest_bytes:
        manifest.write_bytes(manifest_bytes)
    return written, unchanged, removed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Split the MemoX V3 handoff JSON into Markdown.")
    parser.add_argument("input", type=Path, help="handoff JSON file")
    parser.add_argument("output_dir", type=Path, help="directory to (re)generate")
    args = parser.parse_args(argv)

    try:
        raw = args.input.read_bytes()
        data = json.loads(raw.decode("utf-8-sig"))
        outputs = build_outputs(data, args.input.name, hashlib.sha256(raw).hexdigest())
    except (OSError, ValueError, SplitError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    written, unchanged, removed = write_outputs(args.output_dir, outputs)
    print(f"{len(outputs)} files: {written} written, {unchanged} unchanged, {removed} removed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
